// Copyright (c) 2026 The Brave Authors. All rights reserved.
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this file,
// You can obtain one at https://mozilla.org/MPL/2.0/.

// Sync protocol datatype extension for AI Chat conversations.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.6.1
// source: ai_chat_specifics.proto

package sync_pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Represents a complete AI Chat conversation including all entries and events.
// Each sync entity corresponds to one conversation.
type AIChatConversationSpecifics struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Unique identifier for this conversation. Used as client tag and storage
	// key.
	Uuid                            *string                         `protobuf:"bytes,1,opt,name=uuid" json:"uuid,omitempty"`
	Title                           *string                         `protobuf:"bytes,2,opt,name=title" json:"title,omitempty"`
	ModelKey                        *string                         `protobuf:"bytes,3,opt,name=model_key,json=modelKey" json:"model_key,omitempty"`
	TotalTokens                     *uint64                         `protobuf:"varint,4,opt,name=total_tokens,json=totalTokens" json:"total_tokens,omitempty"`
	TrimmedTokens                   *uint64                         `protobuf:"varint,5,opt,name=trimmed_tokens,json=trimmedTokens" json:"trimmed_tokens,omitempty"`
	CreatedTimeUnixEpochMicros      *int64                          `protobuf:"varint,6,opt,name=created_time_unix_epoch_micros,json=createdTimeUnixEpochMicros" json:"created_time_unix_epoch_micros,omitempty"`
	LastModifiedTimeUnixEpochMicros *int64                          `protobuf:"varint,7,opt,name=last_modified_time_unix_epoch_micros,json=lastModifiedTimeUnixEpochMicros" json:"last_modified_time_unix_epoch_micros,omitempty"`
	AssociatedContent               []*AIChatAssociatedContentProto `protobuf:"bytes,8,rep,name=associated_content,json=associatedContent" json:"associated_content,omitempty"`
	Entries                         []*AIChatConversationEntryProto `protobuf:"bytes,9,rep,name=entries" json:"entries,omitempty"`
}

func (x *AIChatConversationSpecifics) Reset() {
	*x = AIChatConversationSpecifics{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ai_chat_specifics_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AIChatConversationSpecifics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AIChatConversationSpecifics) ProtoMessage() {}

func (x *AIChatConversationSpecifics) ProtoReflect() protoreflect.Message {
	mi := &file_ai_chat_specifics_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AIChatConversationSpecifics.ProtoReflect.Descriptor instead.
func (*AIChatConversationSpecifics) Descriptor() ([]byte, []int) {
	return file_ai_chat_specifics_proto_rawDescGZIP(), []int{0}
}

func (x *AIChatConversationSpecifics) GetUuid() string {
	if x != nil && x.Uuid != nil {
		return *x.Uuid
	}
	return ""
}

func (x *AIChatConversationSpecifics) GetTitle() string {
	if x != nil && x.Title != nil {
		return *x.Title
	}
	return ""
}

func (x *AIChatConversationSpecifics) GetModelKey() string {
	if x != nil && x.ModelKey != nil {
		return *x.ModelKey
	}
	return ""
}

func (x *AIChatConversationSpecifics) GetTotalTokens() uint64 {
	if x != nil && x.TotalTokens != nil {
		return *x.TotalTokens
	}
	return 0
}

func (x *AIChatConversationSpecifics) GetTrimmedTokens() uint64 {
	if x != nil && x.TrimmedTokens != nil {
		return *x.TrimmedTokens
	}
	return 0
}

func (x *AIChatConversationSpecifics) GetCreatedTimeUnixEpochMicros() int64 {
	if x != nil && x.CreatedTimeUnixEpochMicros != nil {
		return *x.CreatedTimeUnixEpochMicros
	}
	return 0
}

func (x *AIChatConversationSpecifics) GetLastModifiedTimeUnixEpochMicros() int64 {
	if x != nil && x.LastModifiedTimeUnixEpochMicros != nil {
		return *x.LastModifiedTimeUnixEpochMicros
	}
	return 0
}

func (x *AIChatConversationSpecifics) GetAssociatedContent() []*AIChatAssociatedContentProto {
	if x != nil {
		return x.AssociatedContent
	}
	return nil
}

func (x *AIChatConversationSpecifics) GetEntries() []*AIChatConversationEntryProto {
	if x != nil {
		return x.Entries
	}
	return nil
}

// Metadata for content associated with a conversation (e.g. a web page).
// Full text content is not synced as it can be large and re-derivable.
type AIChatAssociatedContentProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uuid  *string `protobuf:"bytes,1,opt,name=uuid" json:"uuid,omitempty"`
	Title *string `protobuf:"bytes,2,opt,name=title" json:"title,omitempty"`
	Url   *string `protobuf:"bytes,3,opt,name=url" json:"url,omitempty"`
	// mojom::ContentType (0=PageContent, 1=VideoTranscript)
	ContentType           *int32 `protobuf:"varint,4,opt,name=content_type,json=contentType" json:"content_type,omitempty"`
	ContentUsedPercentage *int32 `protobuf:"varint,5,opt,name=content_used_percentage,json=contentUsedPercentage" json:"content_used_percentage,omitempty"`
	// The conversation entry this content is associated with.
	ConversationEntryUuid *string `protobuf:"bytes,6,opt,name=conversation_entry_uuid,json=conversationEntryUuid" json:"conversation_entry_uuid,omitempty"`
}

func (x *AIChatAssociatedContentProto) Reset() {
	*x = AIChatAssociatedContentProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ai_chat_specifics_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AIChatAssociatedContentProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AIChatAssociatedContentProto) ProtoMessage() {}

func (x *AIChatAssociatedContentProto) ProtoReflect() protoreflect.Message {
	mi := &file_ai_chat_specifics_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AIChatAssociatedContentProto.ProtoReflect.Descriptor instead.
func (*AIChatAssociatedContentProto) Descriptor() ([]byte, []int) {
	return file_ai_chat_specifics_proto_rawDescGZIP(), []int{1}
}

func (x *AIChatAssociatedContentProto) GetUuid() string {
	if x != nil && x.Uuid != nil {
		return *x.Uuid
	}
	return ""
}

func (x *AIChatAssociatedContentProto) GetTitle() string {
	if x != nil && x.Title != nil {
		return *x.Title
	}
	return ""
}

func (x *AIChatAssociatedContentProto) GetUrl() string {
	if x != nil && x.Url != nil {
		return *x.Url
	}
	return ""
}

func (x *AIChatAssociatedContentProto) GetContentType() int32 {
	if x != nil && x.ContentType != nil {
		return *x.ContentType
	}
	return 0
}

func (x *AIChatAssociatedContentProto) GetContentUsedPercentage() int32 {
	if x != nil && x.ContentUsedPercentage != nil {
		return *x.ContentUsedPercentage
	}
	return 0
}

func (x *AIChatAssociatedContentProto) GetConversationEntryUuid() string {
	if x != nil && x.ConversationEntryUuid != nil {
		return *x.ConversationEntryUuid
	}
	return ""
}

// A single turn in the conversation (human or assistant message).
type AIChatConversationEntryProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uuid                *string `protobuf:"bytes,1,opt,name=uuid" json:"uuid,omitempty"`
	DateUnixEpochMicros *int64  `protobuf:"varint,2,opt,name=date_unix_epoch_micros,json=dateUnixEpochMicros" json:"date_unix_epoch_micros,omitempty"`
	EntryText           *string `protobuf:"bytes,3,opt,name=entry_text,json=entryText" json:"entry_text,omitempty"`
	// Optional user-invisible override prompt sent to AI engine.
	Prompt *string `protobuf:"bytes,4,opt,name=prompt" json:"prompt,omitempty"`
	// mojom::CharacterType (0=HUMAN, 1=ASSISTANT)
	CharacterType *int32 `protobuf:"varint,5,opt,name=character_type,json=characterType" json:"character_type,omitempty"`
	// UUID of the parent entry being edited (for edit history tracking).
	EditingEntryUuid *string `protobuf:"bytes,6,opt,name=editing_entry_uuid,json=editingEntryUuid" json:"editing_entry_uuid,omitempty"`
	// mojom::ActionType enum
	ActionType *int32 `protobuf:"varint,7,opt,name=action_type,json=actionType" json:"action_type,omitempty"`
	// Selected text from page context.
	SelectedText *string `protobuf:"bytes,8,opt,name=selected_text,json=selectedText" json:"selected_text,omitempty"`
	ModelKey     *string `protobuf:"bytes,9,opt,name=model_key,json=modelKey" json:"model_key,omitempty"`
	// Serialized skill data.
	SmartModeData []byte `protobuf:"bytes,10,opt,name=smart_mode_data,json=smartModeData" json:"smart_mode_data,omitempty"`
	// NEAR AI TEE attestation verification status.
	IsNearVerified *bool                    `protobuf:"varint,11,opt,name=is_near_verified,json=isNearVerified" json:"is_near_verified,omitempty"`
	Events         []*AIChatEntryEventProto `protobuf:"bytes,12,rep,name=events" json:"events,omitempty"`
}

func (x *AIChatConversationEntryProto) Reset() {
	*x = AIChatConversationEntryProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ai_chat_specifics_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AIChatConversationEntryProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AIChatConversationEntryProto) ProtoMessage() {}

func (x *AIChatConversationEntryProto) ProtoReflect() protoreflect.Message {
	mi := &file_ai_chat_specifics_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AIChatConversationEntryProto.ProtoReflect.Descriptor instead.
func (*AIChatConversationEntryProto) Descriptor() ([]byte, []int) {
	return file_ai_chat_specifics_proto_rawDescGZIP(), []int{2}
}

func (x *AIChatConversationEntryProto) GetUuid() string {
	if x != nil && x.Uuid != nil {
		return *x.Uuid
	}
	return ""
}

func (x *AIChatConversationEntryProto) GetDateUnixEpochMicros() int64 {
	if x != nil && x.DateUnixEpochMicros != nil {
		return *x.DateUnixEpochMicros
	}
	return 0
}

func (x *AIChatConversationEntryProto) GetEntryText() string {
	if x != nil && x.EntryText != nil {
		return *x.EntryText
	}
	return ""
}

func (x *AIChatConversationEntryProto) GetPrompt() string {
	if x != nil && x.Prompt != nil {
		return *x.Prompt
	}
	return ""
}

func (x *AIChatConversationEntryProto) GetCharacterType() int32 {
	if x != nil && x.CharacterType != nil {
		return *x.CharacterType
	}
	return 0
}

func (x *AIChatConversationEntryProto) GetEditingEntryUuid() string {
	if x != nil && x.EditingEntryUuid != nil {
		return *x.EditingEntryUuid
	}
	return ""
}

func (x *AIChatConversationEntryProto) GetActionType() int32 {
	if x != nil && x.ActionType != nil {
		return *x.ActionType
	}
	return 0
}

func (x *AIChatConversationEntryProto) GetSelectedText() string {
	if x != nil && x.SelectedText != nil {
		return *x.SelectedText
	}
	return ""
}

func (x *AIChatConversationEntryProto) GetModelKey() string {
	if x != nil && x.ModelKey != nil {
		return *x.ModelKey
	}
	return ""
}

func (x *AIChatConversationEntryProto) GetSmartModeData() []byte {
	if x != nil {
		return x.SmartModeData
	}
	return nil
}

func (x *AIChatConversationEntryProto) GetIsNearVerified() bool {
	if x != nil && x.IsNearVerified != nil {
		return *x.IsNearVerified
	}
	return false
}

func (x *AIChatConversationEntryProto) GetEvents() []*AIChatEntryEventProto {
	if x != nil {
		return x.Events
	}
	return nil
}

// An event within a conversation entry.
type AIChatEntryEventProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EventOrder *int32 `protobuf:"varint,1,opt,name=event_order,json=eventOrder" json:"event_order,omitempty"`
	// Types that are assignable to Event:
	//
	//	*AIChatEntryEventProto_CompletionText
	//	*AIChatEntryEventProto_SearchQueries
	//	*AIChatEntryEventProto_WebSources
	//	*AIChatEntryEventProto_InlineSearch
	//	*AIChatEntryEventProto_ToolUse
	Event isAIChatEntryEventProto_Event `protobuf_oneof:"event"`
}

func (x *AIChatEntryEventProto) Reset() {
	*x = AIChatEntryEventProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ai_chat_specifics_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AIChatEntryEventProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AIChatEntryEventProto) ProtoMessage() {}

func (x *AIChatEntryEventProto) ProtoReflect() protoreflect.Message {
	mi := &file_ai_chat_specifics_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AIChatEntryEventProto.ProtoReflect.Descriptor instead.
func (*AIChatEntryEventProto) Descriptor() ([]byte, []int) {
	return file_ai_chat_specifics_proto_rawDescGZIP(), []int{3}
}

func (x *AIChatEntryEventProto) GetEventOrder() int32 {
	if x != nil && x.EventOrder != nil {
		return *x.EventOrder
	}
	return 0
}

func (m *AIChatEntryEventProto) GetEvent() isAIChatEntryEventProto_Event {
	if m != nil {
		return m.Event
	}
	return nil
}

func (x *AIChatEntryEventProto) GetCompletionText() string {
	if x, ok := x.GetEvent().(*AIChatEntryEventProto_CompletionText); ok {
		return x.CompletionText
	}
	return ""
}

func (x *AIChatEntryEventProto) GetSearchQueries() *AIChatSearchQueriesEvent {
	if x, ok := x.GetEvent().(*AIChatEntryEventProto_SearchQueries); ok {
		return x.SearchQueries
	}
	return nil
}

func (x *AIChatEntryEventProto) GetWebSources() *AIChatWebSourcesEvent {
	if x, ok := x.GetEvent().(*AIChatEntryEventProto_WebSources); ok {
		return x.WebSources
	}
	return nil
}

func (x *AIChatEntryEventProto) GetInlineSearch() *AIChatInlineSearchEvent {
	if x, ok := x.GetEvent().(*AIChatEntryEventProto_InlineSearch); ok {
		return x.InlineSearch
	}
	return nil
}

func (x *AIChatEntryEventProto) GetToolUse() *AIChatToolUseEvent {
	if x, ok := x.GetEvent().(*AIChatEntryEventProto_ToolUse); ok {
		return x.ToolUse
	}
	return nil
}

type isAIChatEntryEventProto_Event interface {
	isAIChatEntryEventProto_Event()
}

type AIChatEntryEventProto_CompletionText struct {
	CompletionText string `protobuf:"bytes,2,opt,name=completion_text,json=completionText,oneof"`
}

type AIChatEntryEventProto_SearchQueries struct {
	SearchQueries *AIChatSearchQueriesEvent `protobuf:"bytes,3,opt,name=search_queries,json=searchQueries,oneof"`
}

type AIChatEntryEventProto_WebSources struct {
	WebSources *AIChatWebSourcesEvent `protobuf:"bytes,4,opt,name=web_sources,json=webSources,oneof"`
}

type AIChatEntryEventProto_InlineSearch struct {
	InlineSearch *AIChatInlineSearchEvent `protobuf:"bytes,5,opt,name=inline_search,json=inlineSearch,oneof"`
}

type AIChatEntryEventProto_ToolUse struct {
	ToolUse *AIChatToolUseEvent `protobuf:"bytes,6,opt,name=tool_use,json=toolUse,oneof"`
}

func (*AIChatEntryEventProto_CompletionText) isAIChatEntryEventProto_Event() {}

func (*AIChatEntryEventProto_SearchQueries) isAIChatEntryEventProto_Event() {}

func (*AIChatEntryEventProto_WebSources) isAIChatEntryEventProto_Event() {}

func (*AIChatEntryEventProto_InlineSearch) isAIChatEntryEventProto_Event() {}

func (*AIChatEntryEventProto_ToolUse) isAIChatEntryEventProto_Event() {}

type AIChatSearchQueriesEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Queries []string `protobuf:"bytes,1,rep,name=queries" json:"queries,omitempty"`
}

func (x *AIChatSearchQueriesEvent) Reset() {
	*x = AIChatSearchQueriesEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ai_chat_specifics_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AIChatSearchQueriesEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AIChatSearchQueriesEvent) ProtoMessage() {}

func (x *AIChatSearchQueriesEvent) ProtoReflect() protoreflect.Message {
	mi := &file_ai_chat_specifics_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AIChatSearchQueriesEvent.ProtoReflect.Descriptor instead.
func (*AIChatSearchQueriesEvent) Descriptor() ([]byte, []int) {
	return file_ai_chat_specifics_proto_rawDescGZIP(), []int{4}
}

func (x *AIChatSearchQueriesEvent) GetQueries() []string {
	if x != nil {
		return x.Queries
	}
	return nil
}

// Web search results shown to the user.
type AIChatWebSourcesEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sources []*AIChatWebSource `protobuf:"bytes,1,rep,name=sources" json:"sources,omitempty"`
	// JSON-formatted rich search results passed through to the renderer.
	RichResults []string `protobuf:"bytes,2,rep,name=rich_results,json=richResults" json:"rich_results,omitempty"`
}

func (x *AIChatWebSourcesEvent) Reset() {
	*x = AIChatWebSourcesEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ai_chat_specifics_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AIChatWebSourcesEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AIChatWebSourcesEvent) ProtoMessage() {}

func (x *AIChatWebSourcesEvent) ProtoReflect() protoreflect.Message {
	mi := &file_ai_chat_specifics_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AIChatWebSourcesEvent.ProtoReflect.Descriptor instead.
func (*AIChatWebSourcesEvent) Descriptor() ([]byte, []int) {
	return file_ai_chat_specifics_proto_rawDescGZIP(), []int{5}
}

func (x *AIChatWebSourcesEvent) GetSources() []*AIChatWebSource {
	if x != nil {
		return x.Sources
	}
	return nil
}

func (x *AIChatWebSourcesEvent) GetRichResults() []string {
	if x != nil {
		return x.RichResults
	}
	return nil
}

type AIChatWebSource struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Title         *string  `protobuf:"bytes,1,opt,name=title" json:"title,omitempty"`
	Url           *string  `protobuf:"bytes,2,opt,name=url" json:"url,omitempty"`
	FaviconUrl    *string  `protobuf:"bytes,3,opt,name=favicon_url,json=faviconUrl" json:"favicon_url,omitempty"`
	PageContent   *string  `protobuf:"bytes,4,opt,name=page_content,json=pageContent" json:"page_content,omitempty"`
	ExtraSnippets []string `protobuf:"bytes,5,rep,name=extra_snippets,json=extraSnippets" json:"extra_snippets,omitempty"`
}

func (x *AIChatWebSource) Reset() {
	*x = AIChatWebSource{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ai_chat_specifics_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AIChatWebSource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AIChatWebSource) ProtoMessage() {}

func (x *AIChatWebSource) ProtoReflect() protoreflect.Message {
	mi := &file_ai_chat_specifics_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AIChatWebSource.ProtoReflect.Descriptor instead.
func (*AIChatWebSource) Descriptor() ([]byte, []int) {
	return file_ai_chat_specifics_proto_rawDescGZIP(), []int{6}
}

func (x *AIChatWebSource) GetTitle() string {
	if x != nil && x.Title != nil {
		return *x.Title
	}
	return ""
}

func (x *AIChatWebSource) GetUrl() string {
	if x != nil && x.Url != nil {
		return *x.Url
	}
	return ""
}

func (x *AIChatWebSource) GetFaviconUrl() string {
	if x != nil && x.FaviconUrl != nil {
		return *x.FaviconUrl
	}
	return ""
}

func (x *AIChatWebSource) GetPageContent() string {
	if x != nil && x.PageContent != nil {
		return *x.PageContent
	}
	return ""
}

func (x *AIChatWebSource) GetExtraSnippets() []string {
	if x != nil {
		return x.ExtraSnippets
	}
	return nil
}

// An inline search performed during the conversation.
type AIChatInlineSearchEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Query       *string `protobuf:"bytes,1,opt,name=query" json:"query,omitempty"`
	ResultsJson *string `protobuf:"bytes,2,opt,name=results_json,json=resultsJson" json:"results_json,omitempty"`
}

func (x *AIChatInlineSearchEvent) Reset() {
	*x = AIChatInlineSearchEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ai_chat_specifics_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AIChatInlineSearchEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AIChatInlineSearchEvent) ProtoMessage() {}

func (x *AIChatInlineSearchEvent) ProtoReflect() protoreflect.Message {
	mi := &file_ai_chat_specifics_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AIChatInlineSearchEvent.ProtoReflect.Descriptor instead.
func (*AIChatInlineSearchEvent) Descriptor() ([]byte, []int) {
	return file_ai_chat_specifics_proto_rawDescGZIP(), []int{7}
}

func (x *AIChatInlineSearchEvent) GetQuery() string {
	if x != nil && x.Query != nil {
		return *x.Query
	}
	return ""
}

func (x *AIChatInlineSearchEvent) GetResultsJson() string {
	if x != nil && x.ResultsJson != nil {
		return *x.ResultsJson
	}
	return ""
}

// A tool/function call made during the conversation.
type AIChatToolUseEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ToolName       *string               `protobuf:"bytes,1,opt,name=tool_name,json=toolName" json:"tool_name,omitempty"`
	Id             *string               `protobuf:"bytes,2,opt,name=id" json:"id,omitempty"`
	ArgumentsJson  *string               `protobuf:"bytes,3,opt,name=arguments_json,json=argumentsJson" json:"arguments_json,omitempty"`
	Output         []*AIChatContentBlock `protobuf:"bytes,4,rep,name=output" json:"output,omitempty"`
	IsServerResult *bool                 `protobuf:"varint,5,opt,name=is_server_result,json=isServerResult" json:"is_server_result,omitempty"`
	Artifacts      []*AIChatToolArtifact `protobuf:"bytes,6,rep,name=artifacts" json:"artifacts,omitempty"`
}

func (x *AIChatToolUseEvent) Reset() {
	*x = AIChatToolUseEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ai_chat_specifics_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AIChatToolUseEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AIChatToolUseEvent) ProtoMessage() {}

func (x *AIChatToolUseEvent) ProtoReflect() protoreflect.Message {
	mi := &file_ai_chat_specifics_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AIChatToolUseEvent.ProtoReflect.Descriptor instead.
func (*AIChatToolUseEvent) Descriptor() ([]byte, []int) {
	return file_ai_chat_specifics_proto_rawDescGZIP(), []int{8}
}

func (x *AIChatToolUseEvent) GetToolName() string {
	if x != nil && x.ToolName != nil {
		return *x.ToolName
	}
	return ""
}

func (x *AIChatToolUseEvent) GetId() string {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return ""
}

func (x *AIChatToolUseEvent) GetArgumentsJson() string {
	if x != nil && x.ArgumentsJson != nil {
		return *x.ArgumentsJson
	}
	return ""
}

func (x *AIChatToolUseEvent) GetOutput() []*AIChatContentBlock {
	if x != nil {
		return x.Output
	}
	return nil
}

func (x *AIChatToolUseEvent) GetIsServerResult() bool {
	if x != nil && x.IsServerResult != nil {
		return *x.IsServerResult
	}
	return false
}

func (x *AIChatToolUseEvent) GetArtifacts() []*AIChatToolArtifact {
	if x != nil {
		return x.Artifacts
	}
	return nil
}

type AIChatContentBlock struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Content:
	//
	//	*AIChatContentBlock_ImageContentBlock
	//	*AIChatContentBlock_TextContentBlock
	//	*AIChatContentBlock_WebSourcesContentBlock
	Content isAIChatContentBlock_Content `protobuf_oneof:"content"`
}

func (x *AIChatContentBlock) Reset() {
	*x = AIChatContentBlock{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ai_chat_specifics_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AIChatContentBlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AIChatContentBlock) ProtoMessage() {}

func (x *AIChatContentBlock) ProtoReflect() protoreflect.Message {
	mi := &file_ai_chat_specifics_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AIChatContentBlock.ProtoReflect.Descriptor instead.
func (*AIChatContentBlock) Descriptor() ([]byte, []int) {
	return file_ai_chat_specifics_proto_rawDescGZIP(), []int{9}
}

func (m *AIChatContentBlock) GetContent() isAIChatContentBlock_Content {
	if m != nil {
		return m.Content
	}
	return nil
}

func (x *AIChatContentBlock) GetImageContentBlock() *AIChatImageContentBlock {
	if x, ok := x.GetContent().(*AIChatContentBlock_ImageContentBlock); ok {
		return x.ImageContentBlock
	}
	return nil
}

func (x *AIChatContentBlock) GetTextContentBlock() *AIChatTextContentBlock {
	if x, ok := x.GetContent().(*AIChatContentBlock_TextContentBlock); ok {
		return x.TextContentBlock
	}
	return nil
}

func (x *AIChatContentBlock) GetWebSourcesContentBlock() *AIChatWebSourcesContentBlock {
	if x, ok := x.GetContent().(*AIChatContentBlock_WebSourcesContentBlock); ok {
		return x.WebSourcesContentBlock
	}
	return nil
}

type isAIChatContentBlock_Content interface {
	isAIChatContentBlock_Content()
}

type AIChatContentBlock_ImageContentBlock struct {
	ImageContentBlock *AIChatImageContentBlock `protobuf:"bytes,1,opt,name=image_content_block,json=imageContentBlock,oneof"`
}

type AIChatContentBlock_TextContentBlock struct {
	TextContentBlock *AIChatTextContentBlock `protobuf:"bytes,2,opt,name=text_content_block,json=textContentBlock,oneof"`
}

type AIChatContentBlock_WebSourcesContentBlock struct {
	WebSourcesContentBlock *AIChatWebSourcesContentBlock `protobuf:"bytes,3,opt,name=web_sources_content_block,json=webSourcesContentBlock,oneof"`
}

func (*AIChatContentBlock_ImageContentBlock) isAIChatContentBlock_Content() {}

func (*AIChatContentBlock_TextContentBlock) isAIChatContentBlock_Content() {}

func (*AIChatContentBlock_WebSourcesContentBlock) isAIChatContentBlock_Content() {}

type AIChatImageContentBlock struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ImageUrl *string `protobuf:"bytes,1,opt,name=image_url,json=imageUrl" json:"image_url,omitempty"`
}

func (x *AIChatImageContentBlock) Reset() {
	*x = AIChatImageContentBlock{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ai_chat_specifics_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AIChatImageContentBlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AIChatImageContentBlock) ProtoMessage() {}

func (x *AIChatImageContentBlock) ProtoReflect() protoreflect.Message {
	mi := &file_ai_chat_specifics_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AIChatImageContentBlock.ProtoReflect.Descriptor instead.
func (*AIChatImageContentBlock) Descriptor() ([]byte, []int) {
	return file_ai_chat_specifics_proto_rawDescGZIP(), []int{10}
}

func (x *AIChatImageContentBlock) GetImageUrl() string {
	if x != nil && x.ImageUrl != nil {
		return *x.ImageUrl
	}
	return ""
}

type AIChatTextContentBlock struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Text *string `protobuf:"bytes,1,opt,name=text" json:"text,omitempty"`
}

func (x *AIChatTextContentBlock) Reset() {
	*x = AIChatTextContentBlock{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ai_chat_specifics_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AIChatTextContentBlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AIChatTextContentBlock) ProtoMessage() {}

func (x *AIChatTextContentBlock) ProtoReflect() protoreflect.Message {
	mi := &file_ai_chat_specifics_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AIChatTextContentBlock.ProtoReflect.Descriptor instead.
func (*AIChatTextContentBlock) Descriptor() ([]byte, []int) {
	return file_ai_chat_specifics_proto_rawDescGZIP(), []int{11}
}

func (x *AIChatTextContentBlock) GetText() string {
	if x != nil && x.Text != nil {
		return *x.Text
	}
	return ""
}

type AIChatWebSourcesContentBlock struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sources     []*AIChatWebSource `protobuf:"bytes,1,rep,name=sources" json:"sources,omitempty"`
	Queries     []string           `protobuf:"bytes,2,rep,name=queries" json:"queries,omitempty"`
	RichResults []string           `protobuf:"bytes,3,rep,name=rich_results,json=richResults" json:"rich_results,omitempty"`
}

func (x *AIChatWebSourcesContentBlock) Reset() {
	*x = AIChatWebSourcesContentBlock{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ai_chat_specifics_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AIChatWebSourcesContentBlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AIChatWebSourcesContentBlock) ProtoMessage() {}

func (x *AIChatWebSourcesContentBlock) ProtoReflect() protoreflect.Message {
	mi := &file_ai_chat_specifics_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AIChatWebSourcesContentBlock.ProtoReflect.Descriptor instead.
func (*AIChatWebSourcesContentBlock) Descriptor() ([]byte, []int) {
	return file_ai_chat_specifics_proto_rawDescGZIP(), []int{12}
}

func (x *AIChatWebSourcesContentBlock) GetSources() []*AIChatWebSource {
	if x != nil {
		return x.Sources
	}
	return nil
}

func (x *AIChatWebSourcesContentBlock) GetQueries() []string {
	if x != nil {
		return x.Queries
	}
	return nil
}

func (x *AIChatWebSourcesContentBlock) GetRichResults() []string {
	if x != nil {
		return x.RichResults
	}
	return nil
}

type AIChatToolArtifact struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type        *string `protobuf:"bytes,1,opt,name=type" json:"type,omitempty"`
	ContentJson *string `protobuf:"bytes,2,opt,name=content_json,json=contentJson" json:"content_json,omitempty"`
}

func (x *AIChatToolArtifact) Reset() {
	*x = AIChatToolArtifact{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ai_chat_specifics_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AIChatToolArtifact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AIChatToolArtifact) ProtoMessage() {}

func (x *AIChatToolArtifact) ProtoReflect() protoreflect.Message {
	mi := &file_ai_chat_specifics_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AIChatToolArtifact.ProtoReflect.Descriptor instead.
func (*AIChatToolArtifact) Descriptor() ([]byte, []int) {
	return file_ai_chat_specifics_proto_rawDescGZIP(), []int{13}
}

func (x *AIChatToolArtifact) GetType() string {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return ""
}

func (x *AIChatToolArtifact) GetContentJson() string {
	if x != nil && x.ContentJson != nil {
		return *x.ContentJson
	}
	return ""
}

var File_ai_chat_specifics_proto protoreflect.FileDescriptor

var file_ai_chat_specifics_proto_rawDesc = []byte{
	0x0a, 0x17, 0x61, 0x69, 0x5f, 0x63, 0x68, 0x61, 0x74, 0x5f, 0x73, 0x70, 0x65, 0x63, 0x69, 0x66,
	0x69, 0x63, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x73, 0x79, 0x6e, 0x63, 0x5f,
	0x70, 0x62, 0x22, 0xd8, 0x03, 0x0a, 0x1b, 0x41, 0x49, 0x43, 0x68, 0x61, 0x74, 0x43, 0x6f, 0x6e,
	0x76, 0x65, 0x72, 0x73, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x70, 0x65, 0x63, 0x69, 0x66, 0x69,
	0x63, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x75, 0x75, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x1b, 0x0a, 0x09,
	0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x4b, 0x65, 0x79, 0x12, 0x21, 0x0a, 0x0c, 0x74, 0x6f, 0x74,
	0x61, 0x6c, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x0b, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x73, 0x12, 0x25, 0x0a, 0x0e,
	0x74, 0x72, 0x69, 0x6d, 0x6d, 0x65, 0x64, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x73, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x0d, 0x74, 0x72, 0x69, 0x6d, 0x6d, 0x65, 0x64, 0x54, 0x6f, 0x6b,
	0x65, 0x6e, 0x73, 0x12, 0x42, 0x0a, 0x1e, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x74,
	0x69, 0x6d, 0x65, 0x5f, 0x75, 0x6e, 0x69, 0x78, 0x5f, 0x65, 0x70, 0x6f, 0x63, 0x68, 0x5f, 0x6d,
	0x69, 0x63, 0x72, 0x6f, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x1a, 0x63, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x55, 0x6e, 0x69, 0x78, 0x45, 0x70, 0x6f, 0x63,
	0x68, 0x4d, 0x69, 0x63, 0x72, 0x6f, 0x73, 0x12, 0x4d, 0x0a, 0x24, 0x6c, 0x61, 0x73, 0x74, 0x5f,
	0x6d, 0x6f, 0x64, 0x69, 0x66, 0x69, 0x65, 0x64, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x75, 0x6e,
	0x69, 0x78, 0x5f, 0x65, 0x70, 0x6f, 0x63, 0x68, 0x5f, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x73, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x1f, 0x6c, 0x61, 0x73, 0x74, 0x4d, 0x6f, 0x64, 0x69, 0x66,
	0x69, 0x65, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x55, 0x6e, 0x69, 0x78, 0x45, 0x70, 0x6f, 0x63, 0x68,
	0x4d, 0x69, 0x63, 0x72, 0x6f, 0x73, 0x12, 0x54, 0x0a, 0x12, 0x61, 0x73, 0x73, 0x6f, 0x63, 0x69,
	0x61, 0x74, 0x65, 0x64, 0x5f, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x08, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x25, 0x2e, 0x73, 0x79, 0x6e, 0x63, 0x5f, 0x70, 0x62, 0x2e, 0x41, 0x49, 0x43,
	0x68, 0x61, 0x74, 0x41, 0x73, 0x73, 0x6f, 0x63, 0x69, 0x61, 0x74, 0x65, 0x64, 0x43, 0x6f, 0x6e,
	0x74, 0x65, 0x6e, 0x74, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x52, 0x11, 0x61, 0x73, 0x73, 0x6f, 0x63,
	0x69, 0x61, 0x74, 0x65, 0x64, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x3f, 0x0a, 0x07,
	0x65, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x18, 0x09, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x25, 0x2e,
	0x73, 0x79, 0x6e, 0x63, 0x5f, 0x70, 0x62, 0x2e, 0x41, 0x49, 0x43, 0x68, 0x61, 0x74, 0x43, 0x6f,
	0x6e, 0x76, 0x65, 0x72, 0x73, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x50,
	0x72, 0x6f, 0x74, 0x6f, 0x52, 0x07, 0x65, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x22, 0xed, 0x01,
	0x0a, 0x1c, 0x41, 0x49, 0x43, 0x68, 0x61, 0x74, 0x41, 0x73, 0x73, 0x6f, 0x63, 0x69, 0x61, 0x74,
	0x65, 0x64, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x12,
	0x0a, 0x04, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x75,
	0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x6f,
	0x6e, 0x74, 0x65, 0x6e, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x0b, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x36, 0x0a,
	0x17, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x5f, 0x75, 0x73, 0x65, 0x64, 0x5f, 0x70, 0x65,
	0x72, 0x63, 0x65, 0x6e, 0x74, 0x61, 0x67, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x15,
	0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x55, 0x73, 0x65, 0x64, 0x50, 0x65, 0x72, 0x63, 0x65,
	0x6e, 0x74, 0x61, 0x67, 0x65, 0x12, 0x36, 0x0a, 0x17, 0x63, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x73,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x65, 0x6e, 0x74, 0x72, 0x79, 0x5f, 0x75, 0x75, 0x69, 0x64,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x15, 0x63, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x73, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x55, 0x75, 0x69, 0x64, 0x22, 0xe0, 0x03,
	0x0a, 0x1c, 0x41, 0x49, 0x43, 0x68, 0x61, 0x74, 0x43, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x73, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x12,
	0x0a, 0x04, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x75,
	0x69, 0x64, 0x12, 0x33, 0x0a, 0x16, 0x64, 0x61, 0x74, 0x65, 0x5f, 0x75, 0x6e, 0x69, 0x78, 0x5f,
	0x65, 0x70, 0x6f, 0x63, 0x68, 0x5f, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x73, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x13, 0x64, 0x61, 0x74, 0x65, 0x55, 0x6e, 0x69, 0x78, 0x45, 0x70, 0x6f, 0x63,
	0x68, 0x4d, 0x69, 0x63, 0x72, 0x6f, 0x73, 0x12, 0x1d, 0x0a, 0x0a, 0x65, 0x6e, 0x74, 0x72, 0x79,
	0x5f, 0x74, 0x65, 0x78, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x65, 0x6e, 0x74,
	0x72, 0x79, 0x54, 0x65, 0x78, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x72, 0x6f, 0x6d, 0x70, 0x74,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x72, 0x6f, 0x6d, 0x70, 0x74, 0x12, 0x25,
	0x0a, 0x0e, 0x63, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x5f, 0x74, 0x79, 0x70, 0x65,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0d, 0x63, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65,
	0x72, 0x54, 0x79, 0x70, 0x65, 0x12, 0x2c, 0x0a, 0x12, 0x65, 0x64, 0x69, 0x74, 0x69, 0x6e, 0x67,
	0x5f, 0x65, 0x6e, 0x74, 0x72, 0x79, 0x5f, 0x75, 0x75, 0x69, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x10, 0x65, 0x64, 0x69, 0x74, 0x69, 0x6e, 0x67, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x55,
	0x75, 0x69, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x73, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x65, 0x64,
	0x5f, 0x74, 0x65, 0x78, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x73, 0x65, 0x6c,
	0x65, 0x63, 0x74, 0x65, 0x64, 0x54, 0x65, 0x78, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x6d, 0x6f, 0x64,
	0x65, 0x6c, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6d, 0x6f,
	0x64, 0x65, 0x6c, 0x4b, 0x65, 0x79, 0x12, 0x26, 0x0a, 0x0f, 0x73, 0x6d, 0x61, 0x72, 0x74, 0x5f,
	0x6d, 0x6f, 0x64, 0x65, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x0d, 0x73, 0x6d, 0x61, 0x72, 0x74, 0x4d, 0x6f, 0x64, 0x65, 0x44, 0x61, 0x74, 0x61, 0x12, 0x28,
	0x0a, 0x10, 0x69, 0x73, 0x5f, 0x6e, 0x65, 0x61, 0x72, 0x5f, 0x76, 0x65, 0x72, 0x69, 0x66, 0x69,
	0x65, 0x64, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0e, 0x69, 0x73, 0x4e, 0x65, 0x61, 0x72,
	0x56, 0x65, 0x72, 0x69, 0x66, 0x69, 0x65, 0x64, 0x12, 0x36, 0x0a, 0x06, 0x65, 0x76, 0x65, 0x6e,
	0x74, 0x73, 0x18, 0x0c, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x73, 0x79, 0x6e, 0x63, 0x5f,
	0x70, 0x62, 0x2e, 0x41, 0x49, 0x43, 0x68, 0x61, 0x74, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x45, 0x76,
	0x65, 0x6e, 0x74, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x52, 0x06, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73,
	0x22, 0xfe, 0x02, 0x0a, 0x15, 0x41, 0x49, 0x43, 0x68, 0x61, 0x74, 0x45, 0x6e, 0x74, 0x72, 0x79,
	0x45, 0x76, 0x65, 0x6e, 0x74, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1f, 0x0a, 0x0b, 0x65, 0x76,
	0x65, 0x6e, 0x74, 0x5f, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x0a, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x12, 0x29, 0x0a, 0x0f, 0x63,
	0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x74, 0x65, 0x78, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x0e, 0x63, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x69,
	0x6f, 0x6e, 0x54, 0x65, 0x78, 0x74, 0x12, 0x4a, 0x0a, 0x0e, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68,
	0x5f, 0x71, 0x75, 0x65, 0x72, 0x69, 0x65, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21,
	0x2e, 0x73, 0x79, 0x6e, 0x63, 0x5f, 0x70, 0x62, 0x2e, 0x41, 0x49, 0x43, 0x68, 0x61, 0x74, 0x53,
	0x65, 0x61, 0x72, 0x63, 0x68, 0x51, 0x75, 0x65, 0x72, 0x69, 0x65, 0x73, 0x45, 0x76, 0x65, 0x6e,
	0x74, 0x48, 0x00, 0x52, 0x0d, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x51, 0x75, 0x65, 0x72, 0x69,
	0x65, 0x73, 0x12, 0x41, 0x0a, 0x0b, 0x77, 0x65, 0x62, 0x5f, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65,
	0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x73, 0x79, 0x6e, 0x63, 0x5f, 0x70,
	0x62, 0x2e, 0x41, 0x49, 0x43, 0x68, 0x61, 0x74, 0x57, 0x65, 0x62, 0x53, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x73, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x48, 0x00, 0x52, 0x0a, 0x77, 0x65, 0x62, 0x53, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x73, 0x12, 0x47, 0x0a, 0x0d, 0x69, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x5f,
	0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x73,
	0x79, 0x6e, 0x63, 0x5f, 0x70, 0x62, 0x2e, 0x41, 0x49, 0x43, 0x68, 0x61, 0x74, 0x49, 0x6e, 0x6c,
	0x69, 0x6e, 0x65, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x48, 0x00,
	0x52, 0x0c, 0x69, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x12, 0x38,
	0x0a, 0x08, 0x74, 0x6f, 0x6f, 0x6c, 0x5f, 0x75, 0x73, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1b, 0x2e, 0x73, 0x79, 0x6e, 0x63, 0x5f, 0x70, 0x62, 0x2e, 0x41, 0x49, 0x43, 0x68, 0x61,
	0x74, 0x54, 0x6f, 0x6f, 0x6c, 0x55, 0x73, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x48, 0x00, 0x52,
	0x07, 0x74, 0x6f, 0x6f, 0x6c, 0x55, 0x73, 0x65, 0x42, 0x07, 0x0a, 0x05, 0x65, 0x76, 0x65, 0x6e,
	0x74, 0x22, 0x34, 0x0a, 0x18, 0x41, 0x49, 0x43, 0x68, 0x61, 0x74, 0x53, 0x65, 0x61, 0x72, 0x63,
	0x68, 0x51, 0x75, 0x65, 0x72, 0x69, 0x65, 0x73, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x18, 0x0a,
	0x07, 0x71, 0x75, 0x65, 0x72, 0x69, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07,
	0x71, 0x75, 0x65, 0x72, 0x69, 0x65, 0x73, 0x22, 0x6e, 0x0a, 0x15, 0x41, 0x49, 0x43, 0x68, 0x61,
	0x74, 0x57, 0x65, 0x62, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x45, 0x76, 0x65, 0x6e, 0x74,
	0x12, 0x32, 0x0a, 0x07, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x18, 0x2e, 0x73, 0x79, 0x6e, 0x63, 0x5f, 0x70, 0x62, 0x2e, 0x41, 0x49, 0x43, 0x68,
	0x61, 0x74, 0x57, 0x65, 0x62, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x07, 0x73, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x73, 0x12, 0x21, 0x0a, 0x0c, 0x72, 0x69, 0x63, 0x68, 0x5f, 0x72, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0b, 0x72, 0x69, 0x63, 0x68,
	0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x22, 0xa4, 0x01, 0x0a, 0x0f, 0x41, 0x49, 0x43, 0x68,
	0x61, 0x74, 0x57, 0x65, 0x62, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74,
	0x69, 0x74, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c,
	0x65, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x75, 0x72, 0x6c, 0x12, 0x1f, 0x0a, 0x0b, 0x66, 0x61, 0x76, 0x69, 0x63, 0x6f, 0x6e, 0x5f, 0x75,
	0x72, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x66, 0x61, 0x76, 0x69, 0x63, 0x6f,
	0x6e, 0x55, 0x72, 0x6c, 0x12, 0x21, 0x0a, 0x0c, 0x70, 0x61, 0x67, 0x65, 0x5f, 0x63, 0x6f, 0x6e,
	0x74, 0x65, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x70, 0x61, 0x67, 0x65,
	0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x25, 0x0a, 0x0e, 0x65, 0x78, 0x74, 0x72, 0x61,
	0x5f, 0x73, 0x6e, 0x69, 0x70, 0x70, 0x65, 0x74, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x0d, 0x65, 0x78, 0x74, 0x72, 0x61, 0x53, 0x6e, 0x69, 0x70, 0x70, 0x65, 0x74, 0x73, 0x22, 0x52,
	0x0a, 0x17, 0x41, 0x49, 0x43, 0x68, 0x61, 0x74, 0x49, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x53, 0x65,
	0x61, 0x72, 0x63, 0x68, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x71, 0x75, 0x65,
	0x72, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x12,
	0x21, 0x0a, 0x0c, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x5f, 0x6a, 0x73, 0x6f, 0x6e, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x4a, 0x73,
	0x6f, 0x6e, 0x22, 0x82, 0x02, 0x0a, 0x12, 0x41, 0x49, 0x43, 0x68, 0x61, 0x74, 0x54, 0x6f, 0x6f,
	0x6c, 0x55, 0x73, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x74, 0x6f, 0x6f,
	0x6c, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x74, 0x6f,
	0x6f, 0x6c, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x25, 0x0a, 0x0e, 0x61, 0x72, 0x67, 0x75, 0x6d, 0x65,
	0x6e, 0x74, 0x73, 0x5f, 0x6a, 0x73, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d,
	0x61, 0x72, 0x67, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x4a, 0x73, 0x6f, 0x6e, 0x12, 0x33, 0x0a,
	0x06, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1b, 0x2e,
	0x73, 0x79, 0x6e, 0x63, 0x5f, 0x70, 0x62, 0x2e, 0x41, 0x49, 0x43, 0x68, 0x61, 0x74, 0x43, 0x6f,
	0x6e, 0x74, 0x65, 0x6e, 0x74, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x06, 0x6f, 0x75, 0x74, 0x70,
	0x75, 0x74, 0x12, 0x28, 0x0a, 0x10, 0x69, 0x73, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f,
	0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0e, 0x69, 0x73,
	0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x39, 0x0a, 0x09,
	0x61, 0x72, 0x74, 0x69, 0x66, 0x61, 0x63, 0x74, 0x73, 0x18, 0x06, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x1b, 0x2e, 0x73, 0x79, 0x6e, 0x63, 0x5f, 0x70, 0x62, 0x2e, 0x41, 0x49, 0x43, 0x68, 0x61, 0x74,
	0x54, 0x6f, 0x6f, 0x6c, 0x41, 0x72, 0x74, 0x69, 0x66, 0x61, 0x63, 0x74, 0x52, 0x09, 0x61, 0x72,
	0x74, 0x69, 0x66, 0x61, 0x63, 0x74, 0x73, 0x22, 0xa8, 0x02, 0x0a, 0x12, 0x41, 0x49, 0x43, 0x68,
	0x61, 0x74, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x12, 0x52,
	0x0a, 0x13, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x5f, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x5f,
	0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x73, 0x79,
	0x6e, 0x63, 0x5f, 0x70, 0x62, 0x2e, 0x41, 0x49, 0x43, 0x68, 0x61, 0x74, 0x49, 0x6d, 0x61, 0x67,
	0x65, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x48, 0x00, 0x52,
	0x11, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x42, 0x6c, 0x6f,
	0x63, 0x6b, 0x12, 0x4f, 0x0a, 0x12, 0x74, 0x65, 0x78, 0x74, 0x5f, 0x63, 0x6f, 0x6e, 0x74, 0x65,
	0x6e, 0x74, 0x5f, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f,
	0x2e, 0x73, 0x79, 0x6e, 0x63, 0x5f, 0x70, 0x62, 0x2e, 0x41, 0x49, 0x43, 0x68, 0x61, 0x74, 0x54,
	0x65, 0x78, 0x74, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x48,
	0x00, 0x52, 0x10, 0x74, 0x65, 0x78, 0x74, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x42, 0x6c,
	0x6f, 0x63, 0x6b, 0x12, 0x62, 0x0a, 0x19, 0x77, 0x65, 0x62, 0x5f, 0x73, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x73, 0x5f, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x5f, 0x62, 0x6c, 0x6f, 0x63, 0x6b,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x73, 0x79, 0x6e, 0x63, 0x5f, 0x70, 0x62,
	0x2e, 0x41, 0x49, 0x43, 0x68, 0x61, 0x74, 0x57, 0x65, 0x62, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65,
	0x73, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x48, 0x00, 0x52,
	0x16, 0x77, 0x65, 0x62, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x43, 0x6f, 0x6e, 0x74, 0x65,
	0x6e, 0x74, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x42, 0x09, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65,
	0x6e, 0x74, 0x22, 0x36, 0x0a, 0x17, 0x41, 0x49, 0x43, 0x68, 0x61, 0x74, 0x49, 0x6d, 0x61, 0x67,
	0x65, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x12, 0x1b, 0x0a,
	0x09, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x55, 0x72, 0x6c, 0x22, 0x2c, 0x0a, 0x16, 0x41, 0x49,
	0x43, 0x68, 0x61, 0x74, 0x54, 0x65, 0x78, 0x74, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x42,
	0x6c, 0x6f, 0x63, 0x6b, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x22, 0x8f, 0x01, 0x0a, 0x1c, 0x41, 0x49, 0x43,
	0x68, 0x61, 0x74, 0x57, 0x65, 0x62, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x43, 0x6f, 0x6e,
	0x74, 0x65, 0x6e, 0x74, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x12, 0x32, 0x0a, 0x07, 0x73, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x73, 0x79, 0x6e,
	0x63, 0x5f, 0x70, 0x62, 0x2e, 0x41, 0x49, 0x43, 0x68, 0x61, 0x74, 0x57, 0x65, 0x62, 0x53, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x52, 0x07, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x12, 0x18, 0x0a,
	0x07, 0x71, 0x75, 0x65, 0x72, 0x69, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07,
	0x71, 0x75, 0x65, 0x72, 0x69, 0x65, 0x73, 0x12, 0x21, 0x0a, 0x0c, 0x72, 0x69, 0x63, 0x68, 0x5f,
	0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0b, 0x72,
	0x69, 0x63, 0x68, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x22, 0x4b, 0x0a, 0x12, 0x41, 0x49,
	0x43, 0x68, 0x61, 0x74, 0x54, 0x6f, 0x6f, 0x6c, 0x41, 0x72, 0x74, 0x69, 0x66, 0x61, 0x63, 0x74,
	0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x5f,
	0x6a, 0x73, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x6f, 0x6e, 0x74,
	0x65, 0x6e, 0x74, 0x4a, 0x73, 0x6f, 0x6e, 0x42, 0x36, 0x0a, 0x25, 0x6f, 0x72, 0x67, 0x2e, 0x63,
	0x68, 0x72, 0x6f, 0x6d, 0x69, 0x75, 0x6d, 0x2e, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e,
	0x74, 0x73, 0x2e, 0x73, 0x79, 0x6e, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c,
	0x48, 0x03, 0x50, 0x01, 0x5a, 0x09, 0x2e, 0x2f, 0x73, 0x79, 0x6e, 0x63, 0x5f, 0x70, 0x62,
}

var (
	file_ai_chat_specifics_proto_rawDescOnce sync.Once
	file_ai_chat_specifics_proto_rawDescData = file_ai_chat_specifics_proto_rawDesc
)

func file_ai_chat_specifics_proto_rawDescGZIP() []byte {
	file_ai_chat_specifics_proto_rawDescOnce.Do(func() {
		file_ai_chat_specifics_proto_rawDescData = protoimpl.X.CompressGZIP(file_ai_chat_specifics_proto_rawDescData)
	})
	return file_ai_chat_specifics_proto_rawDescData
}

var file_ai_chat_specifics_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_ai_chat_specifics_proto_goTypes = []interface{}{
	(*AIChatConversationSpecifics)(nil),  // 0: sync_pb.AIChatConversationSpecifics
	(*AIChatAssociatedContentProto)(nil), // 1: sync_pb.AIChatAssociatedContentProto
	(*AIChatConversationEntryProto)(nil), // 2: sync_pb.AIChatConversationEntryProto
	(*AIChatEntryEventProto)(nil),        // 3: sync_pb.AIChatEntryEventProto
	(*AIChatSearchQueriesEvent)(nil),     // 4: sync_pb.AIChatSearchQueriesEvent
	(*AIChatWebSourcesEvent)(nil),        // 5: sync_pb.AIChatWebSourcesEvent
	(*AIChatWebSource)(nil),              // 6: sync_pb.AIChatWebSource
	(*AIChatInlineSearchEvent)(nil),      // 7: sync_pb.AIChatInlineSearchEvent
	(*AIChatToolUseEvent)(nil),           // 8: sync_pb.AIChatToolUseEvent
	(*AIChatContentBlock)(nil),           // 9: sync_pb.AIChatContentBlock
	(*AIChatImageContentBlock)(nil),      // 10: sync_pb.AIChatImageContentBlock
	(*AIChatTextContentBlock)(nil),       // 11: sync_pb.AIChatTextContentBlock
	(*AIChatWebSourcesContentBlock)(nil), // 12: sync_pb.AIChatWebSourcesContentBlock
	(*AIChatToolArtifact)(nil),           // 13: sync_pb.AIChatToolArtifact
}
var file_ai_chat_specifics_proto_depIdxs = []int32{
	1,  // 0: sync_pb.AIChatConversationSpecifics.associated_content:type_name -> sync_pb.AIChatAssociatedContentProto
	2,  // 1: sync_pb.AIChatConversationSpecifics.entries:type_name -> sync_pb.AIChatConversationEntryProto
	3,  // 2: sync_pb.AIChatConversationEntryProto.events:type_name -> sync_pb.AIChatEntryEventProto
	4,  // 3: sync_pb.AIChatEntryEventProto.search_queries:type_name -> sync_pb.AIChatSearchQueriesEvent
	5,  // 4: sync_pb.AIChatEntryEventProto.web_sources:type_name -> sync_pb.AIChatWebSourcesEvent
	7,  // 5: sync_pb.AIChatEntryEventProto.inline_search:type_name -> sync_pb.AIChatInlineSearchEvent
	8,  // 6: sync_pb.AIChatEntryEventProto.tool_use:type_name -> sync_pb.AIChatToolUseEvent
	6,  // 7: sync_pb.AIChatWebSourcesEvent.sources:type_name -> sync_pb.AIChatWebSource
	9,  // 8: sync_pb.AIChatToolUseEvent.output:type_name -> sync_pb.AIChatContentBlock
	13, // 9: sync_pb.AIChatToolUseEvent.artifacts:type_name -> sync_pb.AIChatToolArtifact
	10, // 10: sync_pb.AIChatContentBlock.image_content_block:type_name -> sync_pb.AIChatImageContentBlock
	11, // 11: sync_pb.AIChatContentBlock.text_content_block:type_name -> sync_pb.AIChatTextContentBlock
	12, // 12: sync_pb.AIChatContentBlock.web_sources_content_block:type_name -> sync_pb.AIChatWebSourcesContentBlock
	6,  // 13: sync_pb.AIChatWebSourcesContentBlock.sources:type_name -> sync_pb.AIChatWebSource
	14, // [14:14] is the sub-list for method output_type
	14, // [14:14] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_ai_chat_specifics_proto_init() }
func file_ai_chat_specifics_proto_init() {
	if File_ai_chat_specifics_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_ai_chat_specifics_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AIChatConversationSpecifics); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ai_chat_specifics_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AIChatAssociatedContentProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ai_chat_specifics_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AIChatConversationEntryProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ai_chat_specifics_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AIChatEntryEventProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ai_chat_specifics_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AIChatSearchQueriesEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ai_chat_specifics_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AIChatWebSourcesEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ai_chat_specifics_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AIChatWebSource); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ai_chat_specifics_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AIChatInlineSearchEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ai_chat_specifics_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AIChatToolUseEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ai_chat_specifics_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AIChatContentBlock); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ai_chat_specifics_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AIChatImageContentBlock); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ai_chat_specifics_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AIChatTextContentBlock); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ai_chat_specifics_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AIChatWebSourcesContentBlock); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ai_chat_specifics_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AIChatToolArtifact); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_ai_chat_specifics_proto_msgTypes[3].OneofWrappers = []interface{}{
		(*AIChatEntryEventProto_CompletionText)(nil),
		(*AIChatEntryEventProto_SearchQueries)(nil),
		(*AIChatEntryEventProto_WebSources)(nil),
		(*AIChatEntryEventProto_InlineSearch)(nil),
		(*AIChatEntryEventProto_ToolUse)(nil),
	}
	file_ai_chat_specifics_proto_msgTypes[9].OneofWrappers = []interface{}{
		(*AIChatContentBlock_ImageContentBlock)(nil),
		(*AIChatContentBlock_TextContentBlock)(nil),
		(*AIChatContentBlock_WebSourcesContentBlock)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ai_chat_specifics_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ai_chat_specifics_proto_goTypes,
		DependencyIndexes: file_ai_chat_specifics_proto_depIdxs,
		MessageInfos:      file_ai_chat_specifics_proto_msgTypes,
	}.Build()
	File_ai_chat_specifics_proto = out.File
	file_ai_chat_specifics_proto_rawDesc = nil
	file_ai_chat_specifics_proto_goTypes = nil
	file_ai_chat_specifics_proto_depIdxs = nil
}
