// Copyright 2016 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
//
// Sync protocol datatype extension for ARC pakcages.

// If you change or add any fields in this file, update proto_visitors.h and
// potentially proto_enum_conversions.{h, cc}.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.21.1
// source: arc_package_specifics.proto

package sync_pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Properties of arc package objects.
type ArcPackageSpecifics struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Unique identifier for the item:
	// Android package name.
	PackageName *string `protobuf:"bytes,1,opt,name=package_name,json=packageName" json:"package_name,omitempty"`
	// Android package version.
	PackageVersion *int32 `protobuf:"varint,2,opt,name=package_version,json=packageVersion" json:"package_version,omitempty"`
	// Last Android id generated when Android side backups data.
	LastBackupAndroidId *int64 `protobuf:"varint,3,opt,name=last_backup_android_id,json=lastBackupAndroidId" json:"last_backup_android_id,omitempty"`
	// Last time internal value that Android side backups data.
	LastBackupTime *int64 `protobuf:"varint,4,opt,name=last_backup_time,json=lastBackupTime" json:"last_backup_time,omitempty"`
}

func (x *ArcPackageSpecifics) Reset() {
	*x = ArcPackageSpecifics{}
	if protoimpl.UnsafeEnabled {
		mi := &file_arc_package_specifics_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ArcPackageSpecifics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArcPackageSpecifics) ProtoMessage() {}

func (x *ArcPackageSpecifics) ProtoReflect() protoreflect.Message {
	mi := &file_arc_package_specifics_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArcPackageSpecifics.ProtoReflect.Descriptor instead.
func (*ArcPackageSpecifics) Descriptor() ([]byte, []int) {
	return file_arc_package_specifics_proto_rawDescGZIP(), []int{0}
}

func (x *ArcPackageSpecifics) GetPackageName() string {
	if x != nil && x.PackageName != nil {
		return *x.PackageName
	}
	return ""
}

func (x *ArcPackageSpecifics) GetPackageVersion() int32 {
	if x != nil && x.PackageVersion != nil {
		return *x.PackageVersion
	}
	return 0
}

func (x *ArcPackageSpecifics) GetLastBackupAndroidId() int64 {
	if x != nil && x.LastBackupAndroidId != nil {
		return *x.LastBackupAndroidId
	}
	return 0
}

func (x *ArcPackageSpecifics) GetLastBackupTime() int64 {
	if x != nil && x.LastBackupTime != nil {
		return *x.LastBackupTime
	}
	return 0
}

var File_arc_package_specifics_proto protoreflect.FileDescriptor

var file_arc_package_specifics_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x61, 0x72, 0x63, 0x5f, 0x70, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x5f, 0x73, 0x70,
	0x65, 0x63, 0x69, 0x66, 0x69, 0x63, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x73,
	0x79, 0x6e, 0x63, 0x5f, 0x70, 0x62, 0x22, 0xc0, 0x01, 0x0a, 0x13, 0x41, 0x72, 0x63, 0x50, 0x61,
	0x63, 0x6b, 0x61, 0x67, 0x65, 0x53, 0x70, 0x65, 0x63, 0x69, 0x66, 0x69, 0x63, 0x73, 0x12, 0x21,
	0x0a, 0x0c, 0x70, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x70, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x4e, 0x61, 0x6d,
	0x65, 0x12, 0x27, 0x0a, 0x0f, 0x70, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x5f, 0x76, 0x65, 0x72,
	0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0e, 0x70, 0x61, 0x63, 0x6b,
	0x61, 0x67, 0x65, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x33, 0x0a, 0x16, 0x6c, 0x61,
	0x73, 0x74, 0x5f, 0x62, 0x61, 0x63, 0x6b, 0x75, 0x70, 0x5f, 0x61, 0x6e, 0x64, 0x72, 0x6f, 0x69,
	0x64, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x13, 0x6c, 0x61, 0x73, 0x74,
	0x42, 0x61, 0x63, 0x6b, 0x75, 0x70, 0x41, 0x6e, 0x64, 0x72, 0x6f, 0x69, 0x64, 0x49, 0x64, 0x12,
	0x28, 0x0a, 0x10, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x62, 0x61, 0x63, 0x6b, 0x75, 0x70, 0x5f, 0x74,
	0x69, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0e, 0x6c, 0x61, 0x73, 0x74, 0x42,
	0x61, 0x63, 0x6b, 0x75, 0x70, 0x54, 0x69, 0x6d, 0x65, 0x42, 0x36, 0x0a, 0x25, 0x6f, 0x72, 0x67,
	0x2e, 0x63, 0x68, 0x72, 0x6f, 0x6d, 0x69, 0x75, 0x6d, 0x2e, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x6e,
	0x65, 0x6e, 0x74, 0x73, 0x2e, 0x73, 0x79, 0x6e, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63,
	0x6f, 0x6c, 0x48, 0x03, 0x50, 0x01, 0x5a, 0x09, 0x2e, 0x2f, 0x73, 0x79, 0x6e, 0x63, 0x5f, 0x70,
	0x62,
}

var (
	file_arc_package_specifics_proto_rawDescOnce sync.Once
	file_arc_package_specifics_proto_rawDescData = file_arc_package_specifics_proto_rawDesc
)

func file_arc_package_specifics_proto_rawDescGZIP() []byte {
	file_arc_package_specifics_proto_rawDescOnce.Do(func() {
		file_arc_package_specifics_proto_rawDescData = protoimpl.X.CompressGZIP(file_arc_package_specifics_proto_rawDescData)
	})
	return file_arc_package_specifics_proto_rawDescData
}

var file_arc_package_specifics_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_arc_package_specifics_proto_goTypes = []interface{}{
	(*ArcPackageSpecifics)(nil), // 0: sync_pb.ArcPackageSpecifics
}
var file_arc_package_specifics_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_arc_package_specifics_proto_init() }
func file_arc_package_specifics_proto_init() {
	if File_arc_package_specifics_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_arc_package_specifics_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ArcPackageSpecifics); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_arc_package_specifics_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_arc_package_specifics_proto_goTypes,
		DependencyIndexes: file_arc_package_specifics_proto_depIdxs,
		MessageInfos:      file_arc_package_specifics_proto_msgTypes,
	}.Build()
	File_arc_package_specifics_proto = out.File
	file_arc_package_specifics_proto_rawDesc = nil
	file_arc_package_specifics_proto_goTypes = nil
	file_arc_package_specifics_proto_depIdxs = nil
}
