// Copyright 2024 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// If you change or add any fields in this file, update proto_visitors.h and
// potentially proto_enum_conversions.{h, cc}.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.6.1
// source: collaboration_group_specifics.proto

package sync_pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Special sync datatype to notify client about People Group changes.
type CollaborationGroupSpecifics struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Unique identifier for a collaboration group, also known as `group_id` or
	// `group_name`.
	CollaborationId *string `protobuf:"bytes,1,opt,name=collaboration_id,json=collaborationId" json:"collaboration_id,omitempty"`
	// Indicates staleness of the collaboration group, used to determine whether
	// client should refresh cached group. Server-side derived from group
	// `consistency_token`.
	LastUpdatedTimestampMillisSinceUnixEpoch *int64 `protobuf:"varint,2,opt,name=last_updated_timestamp_millis_since_unix_epoch,json=lastUpdatedTimestampMillisSinceUnixEpoch" json:"last_updated_timestamp_millis_since_unix_epoch,omitempty"`
}

func (x *CollaborationGroupSpecifics) Reset() {
	*x = CollaborationGroupSpecifics{}
	if protoimpl.UnsafeEnabled {
		mi := &file_collaboration_group_specifics_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CollaborationGroupSpecifics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollaborationGroupSpecifics) ProtoMessage() {}

func (x *CollaborationGroupSpecifics) ProtoReflect() protoreflect.Message {
	mi := &file_collaboration_group_specifics_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollaborationGroupSpecifics.ProtoReflect.Descriptor instead.
func (*CollaborationGroupSpecifics) Descriptor() ([]byte, []int) {
	return file_collaboration_group_specifics_proto_rawDescGZIP(), []int{0}
}

func (x *CollaborationGroupSpecifics) GetCollaborationId() string {
	if x != nil && x.CollaborationId != nil {
		return *x.CollaborationId
	}
	return ""
}

func (x *CollaborationGroupSpecifics) GetLastUpdatedTimestampMillisSinceUnixEpoch() int64 {
	if x != nil && x.LastUpdatedTimestampMillisSinceUnixEpoch != nil {
		return *x.LastUpdatedTimestampMillisSinceUnixEpoch
	}
	return 0
}

var File_collaboration_group_specifics_proto protoreflect.FileDescriptor

var file_collaboration_group_specifics_proto_rawDesc = []byte{
	0x0a, 0x23, 0x63, 0x6f, 0x6c, 0x6c, 0x61, 0x62, 0x6f, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f,
	0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x73, 0x70, 0x65, 0x63, 0x69, 0x66, 0x69, 0x63, 0x73, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x73, 0x79, 0x6e, 0x63, 0x5f, 0x70, 0x62, 0x22, 0xaa,
	0x01, 0x0a, 0x1b, 0x43, 0x6f, 0x6c, 0x6c, 0x61, 0x62, 0x6f, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x47, 0x72, 0x6f, 0x75, 0x70, 0x53, 0x70, 0x65, 0x63, 0x69, 0x66, 0x69, 0x63, 0x73, 0x12, 0x29,
	0x0a, 0x10, 0x63, 0x6f, 0x6c, 0x6c, 0x61, 0x62, 0x6f, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x63, 0x6f, 0x6c, 0x6c, 0x61, 0x62,
	0x6f, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x60, 0x0a, 0x2e, 0x6c, 0x61, 0x73,
	0x74, 0x5f, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x5f, 0x6d, 0x69, 0x6c, 0x6c, 0x69, 0x73, 0x5f, 0x73, 0x69, 0x6e, 0x63, 0x65,
	0x5f, 0x75, 0x6e, 0x69, 0x78, 0x5f, 0x65, 0x70, 0x6f, 0x63, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x28, 0x6c, 0x61, 0x73, 0x74, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x54, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x4d, 0x69, 0x6c, 0x6c, 0x69, 0x73, 0x53, 0x69, 0x6e,
	0x63, 0x65, 0x55, 0x6e, 0x69, 0x78, 0x45, 0x70, 0x6f, 0x63, 0x68, 0x42, 0x36, 0x0a, 0x25, 0x6f,
	0x72, 0x67, 0x2e, 0x63, 0x68, 0x72, 0x6f, 0x6d, 0x69, 0x75, 0x6d, 0x2e, 0x63, 0x6f, 0x6d, 0x70,
	0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x73, 0x79, 0x6e, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x63, 0x6f, 0x6c, 0x48, 0x03, 0x50, 0x01, 0x5a, 0x09, 0x2e, 0x2f, 0x73, 0x79, 0x6e, 0x63,
	0x5f, 0x70, 0x62,
}

var (
	file_collaboration_group_specifics_proto_rawDescOnce sync.Once
	file_collaboration_group_specifics_proto_rawDescData = file_collaboration_group_specifics_proto_rawDesc
)

func file_collaboration_group_specifics_proto_rawDescGZIP() []byte {
	file_collaboration_group_specifics_proto_rawDescOnce.Do(func() {
		file_collaboration_group_specifics_proto_rawDescData = protoimpl.X.CompressGZIP(file_collaboration_group_specifics_proto_rawDescData)
	})
	return file_collaboration_group_specifics_proto_rawDescData
}

var file_collaboration_group_specifics_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_collaboration_group_specifics_proto_goTypes = []interface{}{
	(*CollaborationGroupSpecifics)(nil), // 0: sync_pb.CollaborationGroupSpecifics
}
var file_collaboration_group_specifics_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_collaboration_group_specifics_proto_init() }
func file_collaboration_group_specifics_proto_init() {
	if File_collaboration_group_specifics_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_collaboration_group_specifics_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CollaborationGroupSpecifics); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_collaboration_group_specifics_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_collaboration_group_specifics_proto_goTypes,
		DependencyIndexes: file_collaboration_group_specifics_proto_depIdxs,
		MessageInfos:      file_collaboration_group_specifics_proto_msgTypes,
	}.Build()
	File_collaboration_group_specifics_proto = out.File
	file_collaboration_group_specifics_proto_rawDesc = nil
	file_collaboration_group_specifics_proto_goTypes = nil
	file_collaboration_group_specifics_proto_depIdxs = nil
}
