// Code generated by protoc-gen-go. DO NOT EDIT.
// source: os_preference_specifics.proto

package sync_pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Properties of a synced Chrome OS system preference. Uses PreferenceSpecifics
// instead of declaring name and value fields to allow more code sharing in the
// client (e.g. all PrefModelAssociators can operate on PreferenceSpecifics).
type OsPreferenceSpecifics struct {
	Preference           *PreferenceSpecifics `protobuf:"bytes,1,opt,name=preference" json:"preference,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *OsPreferenceSpecifics) Reset()         { *m = OsPreferenceSpecifics{} }
func (m *OsPreferenceSpecifics) String() string { return proto.CompactTextString(m) }
func (*OsPreferenceSpecifics) ProtoMessage()    {}
func (*OsPreferenceSpecifics) Descriptor() ([]byte, []int) {
	return fileDescriptor_6cad16b4bcb530bc, []int{0}
}

func (m *OsPreferenceSpecifics) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OsPreferenceSpecifics.Unmarshal(m, b)
}
func (m *OsPreferenceSpecifics) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OsPreferenceSpecifics.Marshal(b, m, deterministic)
}
func (m *OsPreferenceSpecifics) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OsPreferenceSpecifics.Merge(m, src)
}
func (m *OsPreferenceSpecifics) XXX_Size() int {
	return xxx_messageInfo_OsPreferenceSpecifics.Size(m)
}
func (m *OsPreferenceSpecifics) XXX_DiscardUnknown() {
	xxx_messageInfo_OsPreferenceSpecifics.DiscardUnknown(m)
}

var xxx_messageInfo_OsPreferenceSpecifics proto.InternalMessageInfo

func (m *OsPreferenceSpecifics) GetPreference() *PreferenceSpecifics {
	if m != nil {
		return m.Preference
	}
	return nil
}

func init() {
	proto.RegisterType((*OsPreferenceSpecifics)(nil), "sync_pb.OsPreferenceSpecifics")
}

func init() {
	proto.RegisterFile("os_preference_specifics.proto", fileDescriptor_6cad16b4bcb530bc)
}

var fileDescriptor_6cad16b4bcb530bc = []byte{
	// 142 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0xcd, 0x2f, 0x8e, 0x2f,
	0x28, 0x4a, 0x4d, 0x4b, 0x2d, 0x4a, 0xcd, 0x4b, 0x4e, 0x8d, 0x2f, 0x2e, 0x48, 0x4d, 0xce, 0x4c,
	0xcb, 0x4c, 0x2e, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2f, 0xae, 0xcc, 0x4b, 0x8e,
	0x2f, 0x48, 0x92, 0x92, 0xc2, 0xad, 0x48, 0x29, 0x94, 0x4b, 0xd4, 0xbf, 0x38, 0x00, 0x2e, 0x1f,
	0x0c, 0x93, 0x16, 0xb2, 0xe1, 0xe2, 0x42, 0x68, 0x93, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x36, 0x92,
	0xd1, 0x83, 0x1a, 0xa9, 0x87, 0x45, 0x47, 0x10, 0x92, 0x7a, 0x27, 0x6d, 0x2e, 0xd5, 0xfc, 0xa2,
	0x74, 0xbd, 0xe4, 0x8c, 0xa2, 0xfc, 0xdc, 0xcc, 0xd2, 0x5c, 0xbd, 0xe4, 0xfc, 0xdc, 0x82, 0xfc,
	0xbc, 0xd4, 0xbc, 0x92, 0x62, 0xb0, 0x11, 0x10, 0xcb, 0x93, 0xf3, 0x73, 0x3c, 0x98, 0x03, 0x18,
	0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x1e, 0x6f, 0x48, 0x60, 0xc8, 0x00, 0x00, 0x00,
}
