// Copyright 2021 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// If you change or add any fields in this file, update proto_visitors.h and
// potentially proto_enum_conversions.{h, cc}.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.24.0
// 	protoc        v3.12.2
// source: password_with_local_data.proto

package sync_pb

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// Wrapper for a set of credentials that consists of (possibly) synced password
// data and local data that is exclusively read and modified by Chrome.
type PasswordWithLocalData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// A potentially synced set of credentials.
	PasswordSpecificsData *PasswordSpecificsData `protobuf:"bytes,1,opt,name=password_specifics_data,json=passwordSpecificsData" json:"password_specifics_data,omitempty"`
	// Local data that is related to the `password_specifics_data`. Although it is
	// stored close to the `password_specifics_data`, it always stays local to the
	// device the password is stored on and is never synced. The provider does not
	// read or modify it -- only Chrome does.
	// This data will for example contain `FormData` or device-specific properties
	// like `PasswordForm::skip_zero_click` that prevents a credential to be used
	// for Credential Management requests on this device.
	LocalChromeData []byte `protobuf:"bytes,2,opt,name=local_chrome_data,json=localChromeData" json:"local_chrome_data,omitempty"`
}

func (x *PasswordWithLocalData) Reset() {
	*x = PasswordWithLocalData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_password_with_local_data_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PasswordWithLocalData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PasswordWithLocalData) ProtoMessage() {}

func (x *PasswordWithLocalData) ProtoReflect() protoreflect.Message {
	mi := &file_password_with_local_data_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PasswordWithLocalData.ProtoReflect.Descriptor instead.
func (*PasswordWithLocalData) Descriptor() ([]byte, []int) {
	return file_password_with_local_data_proto_rawDescGZIP(), []int{0}
}

func (x *PasswordWithLocalData) GetPasswordSpecificsData() *PasswordSpecificsData {
	if x != nil {
		return x.PasswordSpecificsData
	}
	return nil
}

func (x *PasswordWithLocalData) GetLocalChromeData() []byte {
	if x != nil {
		return x.LocalChromeData
	}
	return nil
}

var File_password_with_local_data_proto protoreflect.FileDescriptor

var file_password_with_local_data_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x5f, 0x77, 0x69, 0x74, 0x68, 0x5f,
	0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x07, 0x73, 0x79, 0x6e, 0x63, 0x5f, 0x70, 0x62, 0x1a, 0x18, 0x70, 0x61, 0x73, 0x73, 0x77,
	0x6f, 0x72, 0x64, 0x5f, 0x73, 0x70, 0x65, 0x63, 0x69, 0x66, 0x69, 0x63, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x9b, 0x01, 0x0a, 0x15, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64,
	0x57, 0x69, 0x74, 0x68, 0x4c, 0x6f, 0x63, 0x61, 0x6c, 0x44, 0x61, 0x74, 0x61, 0x12, 0x56, 0x0a,
	0x17, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x5f, 0x73, 0x70, 0x65, 0x63, 0x69, 0x66,
	0x69, 0x63, 0x73, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e,
	0x2e, 0x73, 0x79, 0x6e, 0x63, 0x5f, 0x70, 0x62, 0x2e, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72,
	0x64, 0x53, 0x70, 0x65, 0x63, 0x69, 0x66, 0x69, 0x63, 0x73, 0x44, 0x61, 0x74, 0x61, 0x52, 0x15,
	0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x53, 0x70, 0x65, 0x63, 0x69, 0x66, 0x69, 0x63,
	0x73, 0x44, 0x61, 0x74, 0x61, 0x12, 0x2a, 0x0a, 0x11, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x5f, 0x63,
	0x68, 0x72, 0x6f, 0x6d, 0x65, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x0f, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x43, 0x68, 0x72, 0x6f, 0x6d, 0x65, 0x44, 0x61, 0x74,
	0x61, 0x42, 0x2b, 0x0a, 0x25, 0x6f, 0x72, 0x67, 0x2e, 0x63, 0x68, 0x72, 0x6f, 0x6d, 0x69, 0x75,
	0x6d, 0x2e, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x73, 0x79, 0x6e,
	0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x48, 0x03, 0x50, 0x01,
}

var (
	file_password_with_local_data_proto_rawDescOnce sync.Once
	file_password_with_local_data_proto_rawDescData = file_password_with_local_data_proto_rawDesc
)

func file_password_with_local_data_proto_rawDescGZIP() []byte {
	file_password_with_local_data_proto_rawDescOnce.Do(func() {
		file_password_with_local_data_proto_rawDescData = protoimpl.X.CompressGZIP(file_password_with_local_data_proto_rawDescData)
	})
	return file_password_with_local_data_proto_rawDescData
}

var file_password_with_local_data_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_password_with_local_data_proto_goTypes = []interface{}{
	(*PasswordWithLocalData)(nil), // 0: sync_pb.PasswordWithLocalData
	(*PasswordSpecificsData)(nil), // 1: sync_pb.PasswordSpecificsData
}
var file_password_with_local_data_proto_depIdxs = []int32{
	1, // 0: sync_pb.PasswordWithLocalData.password_specifics_data:type_name -> sync_pb.PasswordSpecificsData
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_password_with_local_data_proto_init() }
func file_password_with_local_data_proto_init() {
	if File_password_with_local_data_proto != nil {
		return
	}
	file_password_specifics_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_password_with_local_data_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PasswordWithLocalData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_password_with_local_data_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_password_with_local_data_proto_goTypes,
		DependencyIndexes: file_password_with_local_data_proto_depIdxs,
		MessageInfos:      file_password_with_local_data_proto_msgTypes,
	}.Build()
	File_password_with_local_data_proto = out.File
	file_password_with_local_data_proto_rawDesc = nil
	file_password_with_local_data_proto_goTypes = nil
	file_password_with_local_data_proto_depIdxs = nil
}
