// Code generated by protoc-gen-go. DO NOT EDIT.
// source: reading_list_specifics.proto

package sync_pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ReadingListSpecifics_ReadingListEntryStatus int32

const (
	ReadingListSpecifics_UNREAD ReadingListSpecifics_ReadingListEntryStatus = 0
	ReadingListSpecifics_READ   ReadingListSpecifics_ReadingListEntryStatus = 1
	ReadingListSpecifics_UNSEEN ReadingListSpecifics_ReadingListEntryStatus = 2
)

var ReadingListSpecifics_ReadingListEntryStatus_name = map[int32]string{
	0: "UNREAD",
	1: "READ",
	2: "UNSEEN",
}

var ReadingListSpecifics_ReadingListEntryStatus_value = map[string]int32{
	"UNREAD": 0,
	"READ":   1,
	"UNSEEN": 2,
}

func (x ReadingListSpecifics_ReadingListEntryStatus) Enum() *ReadingListSpecifics_ReadingListEntryStatus {
	p := new(ReadingListSpecifics_ReadingListEntryStatus)
	*p = x
	return p
}

func (x ReadingListSpecifics_ReadingListEntryStatus) String() string {
	return proto.EnumName(ReadingListSpecifics_ReadingListEntryStatus_name, int32(x))
}

func (x *ReadingListSpecifics_ReadingListEntryStatus) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ReadingListSpecifics_ReadingListEntryStatus_value, data, "ReadingListSpecifics_ReadingListEntryStatus")
	if err != nil {
		return err
	}
	*x = ReadingListSpecifics_ReadingListEntryStatus(value)
	return nil
}

func (ReadingListSpecifics_ReadingListEntryStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_3523217d96e31cba, []int{0, 0}
}

// Sync Reading list entry. This proto contains the fields synced for a reading
// list entry. It must be kept synced with the reading_list.ReadingListLocal
// protobuf.
type ReadingListSpecifics struct {
	EntryId           *string `protobuf:"bytes,1,opt,name=entry_id,json=entryId" json:"entry_id,omitempty"`
	Title             *string `protobuf:"bytes,2,opt,name=title" json:"title,omitempty"`
	Url               *string `protobuf:"bytes,3,opt,name=url" json:"url,omitempty"`
	CreationTimeUs    *int64  `protobuf:"varint,4,opt,name=creation_time_us,json=creationTimeUs" json:"creation_time_us,omitempty"`
	UpdateTimeUs      *int64  `protobuf:"varint,5,opt,name=update_time_us,json=updateTimeUs" json:"update_time_us,omitempty"`
	FirstReadTimeUs   *int64  `protobuf:"varint,7,opt,name=first_read_time_us,json=firstReadTimeUs" json:"first_read_time_us,omitempty"`
	UpdateTitleTimeUs *int64  `protobuf:"varint,8,opt,name=update_title_time_us,json=updateTitleTimeUs" json:"update_title_time_us,omitempty"`
	// If the field is not present, it defaults to UNSEEN.
	Status               *ReadingListSpecifics_ReadingListEntryStatus `protobuf:"varint,6,opt,name=status,enum=sync_pb.ReadingListSpecifics_ReadingListEntryStatus" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                     `json:"-"`
	XXX_unrecognized     []byte                                       `json:"-"`
	XXX_sizecache        int32                                        `json:"-"`
}

func (m *ReadingListSpecifics) Reset()         { *m = ReadingListSpecifics{} }
func (m *ReadingListSpecifics) String() string { return proto.CompactTextString(m) }
func (*ReadingListSpecifics) ProtoMessage()    {}
func (*ReadingListSpecifics) Descriptor() ([]byte, []int) {
	return fileDescriptor_3523217d96e31cba, []int{0}
}

func (m *ReadingListSpecifics) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadingListSpecifics.Unmarshal(m, b)
}
func (m *ReadingListSpecifics) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadingListSpecifics.Marshal(b, m, deterministic)
}
func (m *ReadingListSpecifics) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadingListSpecifics.Merge(m, src)
}
func (m *ReadingListSpecifics) XXX_Size() int {
	return xxx_messageInfo_ReadingListSpecifics.Size(m)
}
func (m *ReadingListSpecifics) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadingListSpecifics.DiscardUnknown(m)
}

var xxx_messageInfo_ReadingListSpecifics proto.InternalMessageInfo

func (m *ReadingListSpecifics) GetEntryId() string {
	if m != nil && m.EntryId != nil {
		return *m.EntryId
	}
	return ""
}

func (m *ReadingListSpecifics) GetTitle() string {
	if m != nil && m.Title != nil {
		return *m.Title
	}
	return ""
}

func (m *ReadingListSpecifics) GetUrl() string {
	if m != nil && m.Url != nil {
		return *m.Url
	}
	return ""
}

func (m *ReadingListSpecifics) GetCreationTimeUs() int64 {
	if m != nil && m.CreationTimeUs != nil {
		return *m.CreationTimeUs
	}
	return 0
}

func (m *ReadingListSpecifics) GetUpdateTimeUs() int64 {
	if m != nil && m.UpdateTimeUs != nil {
		return *m.UpdateTimeUs
	}
	return 0
}

func (m *ReadingListSpecifics) GetFirstReadTimeUs() int64 {
	if m != nil && m.FirstReadTimeUs != nil {
		return *m.FirstReadTimeUs
	}
	return 0
}

func (m *ReadingListSpecifics) GetUpdateTitleTimeUs() int64 {
	if m != nil && m.UpdateTitleTimeUs != nil {
		return *m.UpdateTitleTimeUs
	}
	return 0
}

func (m *ReadingListSpecifics) GetStatus() ReadingListSpecifics_ReadingListEntryStatus {
	if m != nil && m.Status != nil {
		return *m.Status
	}
	return ReadingListSpecifics_UNREAD
}

func init() {
	proto.RegisterEnum("sync_pb.ReadingListSpecifics_ReadingListEntryStatus", ReadingListSpecifics_ReadingListEntryStatus_name, ReadingListSpecifics_ReadingListEntryStatus_value)
	proto.RegisterType((*ReadingListSpecifics)(nil), "sync_pb.ReadingListSpecifics")
}

func init() {
	proto.RegisterFile("reading_list_specifics.proto", fileDescriptor_3523217d96e31cba)
}

var fileDescriptor_3523217d96e31cba = []byte{
	// 314 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0x4d, 0x4b, 0xf3, 0x40,
	0x10, 0xc7, 0x9f, 0x34, 0x7d, 0x7b, 0x06, 0xa9, 0x71, 0x29, 0x12, 0xc1, 0x43, 0x29, 0x0a, 0x81,
	0x42, 0x04, 0xf1, 0xe4, 0x4d, 0x31, 0xa0, 0x50, 0x8a, 0xa4, 0xf6, 0xbc, 0xc4, 0xcd, 0xb6, 0x0e,
	0x24, 0xd9, 0xb0, 0x3b, 0x39, 0xf4, 0x63, 0xf8, 0x8d, 0x25, 0x9b, 0x17, 0x3d, 0xf4, 0x36, 0xf3,
	0xdb, 0xdf, 0xfe, 0xd9, 0x99, 0x85, 0x6b, 0x2d, 0x93, 0x14, 0x8b, 0x03, 0xcf, 0xd0, 0x10, 0x37,
	0xa5, 0x14, 0xb8, 0x47, 0x61, 0xc2, 0x52, 0x2b, 0x52, 0x6c, 0x62, 0x8e, 0x85, 0xe0, 0xe5, 0xe7,
	0xf2, 0xdb, 0x85, 0x79, 0xdc, 0x98, 0x6b, 0x34, 0xb4, 0xed, 0x3c, 0x76, 0x05, 0x53, 0x59, 0x90,
	0x3e, 0x72, 0x4c, 0x7d, 0x67, 0xe1, 0x04, 0xff, 0xe3, 0x89, 0xed, 0xdf, 0x52, 0x36, 0x87, 0x11,
	0x21, 0x65, 0xd2, 0x1f, 0x58, 0xde, 0x34, 0xcc, 0x03, 0xb7, 0xd2, 0x99, 0xef, 0x5a, 0x56, 0x97,
	0x2c, 0x00, 0x4f, 0x68, 0x99, 0x10, 0xaa, 0x82, 0x13, 0xe6, 0x92, 0x57, 0xc6, 0x1f, 0x2e, 0x9c,
	0xc0, 0x8d, 0x67, 0x1d, 0xff, 0xc0, 0x5c, 0xee, 0x0c, 0xbb, 0x81, 0x59, 0x55, 0xa6, 0x09, 0xc9,
	0xde, 0x1b, 0x59, 0xef, 0xac, 0xa1, 0xad, 0xb5, 0x02, 0xb6, 0x47, 0x6d, 0x88, 0xd7, 0xa3, 0xf5,
	0xe6, 0xc4, 0x9a, 0xe7, 0xf6, 0xa4, 0x9e, 0xa4, 0x95, 0xef, 0x60, 0xde, 0x47, 0x52, 0xf6, 0x1b,
	0x3c, 0xb5, 0xfa, 0x45, 0x17, 0x4c, 0x59, 0x97, 0xbe, 0x86, 0xb1, 0xa1, 0x84, 0x2a, 0xe3, 0x8f,
	0x17, 0x4e, 0x30, 0xbb, 0x7f, 0x08, 0xdb, 0x1d, 0x85, 0xa7, 0xf6, 0xf3, 0x17, 0x46, 0xf5, 0x5e,
	0xb6, 0xf6, 0x6e, 0xdc, 0x66, 0x2c, 0x1f, 0xe1, 0xf2, 0xb4, 0xc1, 0x00, 0xc6, 0xbb, 0x4d, 0x1c,
	0x3d, 0xbd, 0x78, 0xff, 0xd8, 0x14, 0x86, 0xb6, 0x72, 0x1a, 0xba, 0x8d, 0xa2, 0x8d, 0x37, 0x78,
	0x5e, 0xc1, 0xad, 0xd2, 0x87, 0x50, 0x7c, 0x69, 0x95, 0x63, 0x95, 0x87, 0x42, 0xe5, 0xa5, 0x2a,
	0x64, 0x41, 0xc6, 0x3e, 0xa9, 0xf9, 0x42, 0xa1, 0xb2, 0x57, 0xf7, 0xdd, 0xf9, 0x09, 0x00, 0x00,
	0xff, 0xff, 0xa0, 0xfa, 0x0c, 0xda, 0xe8, 0x01, 0x00, 0x00,
}
