// Copyright 2022 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// If you change or add any fields in this file, update proto_visitors.h and
// potentially proto_enum_conversions.{h, cc}.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.6.1
// source: saved_tab_group_specifics.proto

package sync_pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// These colors map to tab_groups::TabGroupColorId. They DO NOT match the enum
// integer values due to "kGrey" being in the "Unspecified" field.
type SavedTabGroup_SavedTabGroupColor int32

const (
	SavedTabGroup_SAVED_TAB_GROUP_COLOR_UNSPECIFIED SavedTabGroup_SavedTabGroupColor = 0
	SavedTabGroup_SAVED_TAB_GROUP_COLOR_GREY        SavedTabGroup_SavedTabGroupColor = 1
	SavedTabGroup_SAVED_TAB_GROUP_COLOR_BLUE        SavedTabGroup_SavedTabGroupColor = 2
	SavedTabGroup_SAVED_TAB_GROUP_COLOR_RED         SavedTabGroup_SavedTabGroupColor = 3
	SavedTabGroup_SAVED_TAB_GROUP_COLOR_YELLOW      SavedTabGroup_SavedTabGroupColor = 4
	SavedTabGroup_SAVED_TAB_GROUP_COLOR_GREEN       SavedTabGroup_SavedTabGroupColor = 5
	SavedTabGroup_SAVED_TAB_GROUP_COLOR_PINK        SavedTabGroup_SavedTabGroupColor = 6
	SavedTabGroup_SAVED_TAB_GROUP_COLOR_PURPLE      SavedTabGroup_SavedTabGroupColor = 7
	SavedTabGroup_SAVED_TAB_GROUP_COLOR_CYAN        SavedTabGroup_SavedTabGroupColor = 8
	SavedTabGroup_SAVED_TAB_GROUP_COLOR_ORANGE      SavedTabGroup_SavedTabGroupColor = 9
)

// Enum value maps for SavedTabGroup_SavedTabGroupColor.
var (
	SavedTabGroup_SavedTabGroupColor_name = map[int32]string{
		0: "SAVED_TAB_GROUP_COLOR_UNSPECIFIED",
		1: "SAVED_TAB_GROUP_COLOR_GREY",
		2: "SAVED_TAB_GROUP_COLOR_BLUE",
		3: "SAVED_TAB_GROUP_COLOR_RED",
		4: "SAVED_TAB_GROUP_COLOR_YELLOW",
		5: "SAVED_TAB_GROUP_COLOR_GREEN",
		6: "SAVED_TAB_GROUP_COLOR_PINK",
		7: "SAVED_TAB_GROUP_COLOR_PURPLE",
		8: "SAVED_TAB_GROUP_COLOR_CYAN",
		9: "SAVED_TAB_GROUP_COLOR_ORANGE",
	}
	SavedTabGroup_SavedTabGroupColor_value = map[string]int32{
		"SAVED_TAB_GROUP_COLOR_UNSPECIFIED": 0,
		"SAVED_TAB_GROUP_COLOR_GREY":        1,
		"SAVED_TAB_GROUP_COLOR_BLUE":        2,
		"SAVED_TAB_GROUP_COLOR_RED":         3,
		"SAVED_TAB_GROUP_COLOR_YELLOW":      4,
		"SAVED_TAB_GROUP_COLOR_GREEN":       5,
		"SAVED_TAB_GROUP_COLOR_PINK":        6,
		"SAVED_TAB_GROUP_COLOR_PURPLE":      7,
		"SAVED_TAB_GROUP_COLOR_CYAN":        8,
		"SAVED_TAB_GROUP_COLOR_ORANGE":      9,
	}
)

func (x SavedTabGroup_SavedTabGroupColor) Enum() *SavedTabGroup_SavedTabGroupColor {
	p := new(SavedTabGroup_SavedTabGroupColor)
	*p = x
	return p
}

func (x SavedTabGroup_SavedTabGroupColor) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SavedTabGroup_SavedTabGroupColor) Descriptor() protoreflect.EnumDescriptor {
	return file_saved_tab_group_specifics_proto_enumTypes[0].Descriptor()
}

func (SavedTabGroup_SavedTabGroupColor) Type() protoreflect.EnumType {
	return &file_saved_tab_group_specifics_proto_enumTypes[0]
}

func (x SavedTabGroup_SavedTabGroupColor) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *SavedTabGroup_SavedTabGroupColor) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = SavedTabGroup_SavedTabGroupColor(num)
	return nil
}

// Deprecated: Use SavedTabGroup_SavedTabGroupColor.Descriptor instead.
func (SavedTabGroup_SavedTabGroupColor) EnumDescriptor() ([]byte, []int) {
	return file_saved_tab_group_specifics_proto_rawDescGZIP(), []int{0, 0}
}

// Sync protocol datatype extension for saved tab groups. Saved Tab Groups are
// tab groups which can be recalled between browser sessions, and if sync is
// turned on, cross device. A saved tab group contains tabs which are stored as
// a SavedTabGroupSpecifics separately (SavedTabGroupTab). This is due to
// limitations from the sync service on the size of an individual sync entity.
type SavedTabGroup struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The position of the SavedTabGroup in any visual display. This also
	// represents the index in the SavedTabGroupModel of the group.
	Position *int64 `protobuf:"varint,1,opt,name=position" json:"position,omitempty"`
	// The displayed title of the group, shown on the tab group and the saved tab
	// group button.
	Title *string `protobuf:"bytes,2,opt,name=title" json:"title,omitempty"`
	// The color of the group, mapped to tab_groups::TabGroupColorId.
	Color *SavedTabGroup_SavedTabGroupColor `protobuf:"varint,3,opt,name=color,enum=sync_pb.SavedTabGroup_SavedTabGroupColor" json:"color,omitempty"`
}

func (x *SavedTabGroup) Reset() {
	*x = SavedTabGroup{}
	if protoimpl.UnsafeEnabled {
		mi := &file_saved_tab_group_specifics_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SavedTabGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SavedTabGroup) ProtoMessage() {}

func (x *SavedTabGroup) ProtoReflect() protoreflect.Message {
	mi := &file_saved_tab_group_specifics_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SavedTabGroup.ProtoReflect.Descriptor instead.
func (*SavedTabGroup) Descriptor() ([]byte, []int) {
	return file_saved_tab_group_specifics_proto_rawDescGZIP(), []int{0}
}

func (x *SavedTabGroup) GetPosition() int64 {
	if x != nil && x.Position != nil {
		return *x.Position
	}
	return 0
}

func (x *SavedTabGroup) GetTitle() string {
	if x != nil && x.Title != nil {
		return *x.Title
	}
	return ""
}

func (x *SavedTabGroup) GetColor() SavedTabGroup_SavedTabGroupColor {
	if x != nil && x.Color != nil {
		return *x.Color
	}
	return SavedTabGroup_SAVED_TAB_GROUP_COLOR_UNSPECIFIED
}

// Sync protocol datatype extension for saved tab group tabs. SavedTabGroupTab
// are the sync representation of a tab in a saved tab group. they are stored as
// separate entities due to size limitations of sync entities.
type SavedTabGroupTab struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// An id that links the saved tab group tab to it's saved tab group.
	GroupGuid *string `protobuf:"bytes,1,opt,name=group_guid,json=groupGuid" json:"group_guid,omitempty"`
	// The position in the Tab Strip the tab is located relative to the start of
	// the tab group. This is also the index in the saved_tabs_ vector in the
	// SavedTabGroup in the SavedTabGroupModel, which is updated by the
	// TabStripModel.
	Position *int64 `protobuf:"varint,2,opt,name=position" json:"position,omitempty"`
	// Tab Data used for constructing the tab.
	Url *string `protobuf:"bytes,3,opt,name=url" json:"url,omitempty"`
	// The displayed title of the tab, shown on the saved tab group button's
	// context menu.
	Title *string `protobuf:"bytes,4,opt,name=title" json:"title,omitempty"`
}

func (x *SavedTabGroupTab) Reset() {
	*x = SavedTabGroupTab{}
	if protoimpl.UnsafeEnabled {
		mi := &file_saved_tab_group_specifics_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SavedTabGroupTab) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SavedTabGroupTab) ProtoMessage() {}

func (x *SavedTabGroupTab) ProtoReflect() protoreflect.Message {
	mi := &file_saved_tab_group_specifics_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SavedTabGroupTab.ProtoReflect.Descriptor instead.
func (*SavedTabGroupTab) Descriptor() ([]byte, []int) {
	return file_saved_tab_group_specifics_proto_rawDescGZIP(), []int{1}
}

func (x *SavedTabGroupTab) GetGroupGuid() string {
	if x != nil && x.GroupGuid != nil {
		return *x.GroupGuid
	}
	return ""
}

func (x *SavedTabGroupTab) GetPosition() int64 {
	if x != nil && x.Position != nil {
		return *x.Position
	}
	return 0
}

func (x *SavedTabGroupTab) GetUrl() string {
	if x != nil && x.Url != nil {
		return *x.Url
	}
	return ""
}

func (x *SavedTabGroupTab) GetTitle() string {
	if x != nil && x.Title != nil {
		return *x.Title
	}
	return ""
}

type SavedTabGroupSpecifics struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// An id that refers to the sync saved tab group object.
	Guid *string `protobuf:"bytes,1,opt,name=guid" json:"guid,omitempty"`
	// Timestamps for CRUD operations.
	CreationTimeWindowsEpochMicros *int64 `protobuf:"varint,2,opt,name=creation_time_windows_epoch_micros,json=creationTimeWindowsEpochMicros" json:"creation_time_windows_epoch_micros,omitempty"`
	UpdateTimeWindowsEpochMicros   *int64 `protobuf:"varint,3,opt,name=update_time_windows_epoch_micros,json=updateTimeWindowsEpochMicros" json:"update_time_windows_epoch_micros,omitempty"`
	// Types that are assignable to Entity:
	//	*SavedTabGroupSpecifics_Group
	//	*SavedTabGroupSpecifics_Tab
	Entity isSavedTabGroupSpecifics_Entity `protobuf_oneof:"entity"`
}

func (x *SavedTabGroupSpecifics) Reset() {
	*x = SavedTabGroupSpecifics{}
	if protoimpl.UnsafeEnabled {
		mi := &file_saved_tab_group_specifics_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SavedTabGroupSpecifics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SavedTabGroupSpecifics) ProtoMessage() {}

func (x *SavedTabGroupSpecifics) ProtoReflect() protoreflect.Message {
	mi := &file_saved_tab_group_specifics_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SavedTabGroupSpecifics.ProtoReflect.Descriptor instead.
func (*SavedTabGroupSpecifics) Descriptor() ([]byte, []int) {
	return file_saved_tab_group_specifics_proto_rawDescGZIP(), []int{2}
}

func (x *SavedTabGroupSpecifics) GetGuid() string {
	if x != nil && x.Guid != nil {
		return *x.Guid
	}
	return ""
}

func (x *SavedTabGroupSpecifics) GetCreationTimeWindowsEpochMicros() int64 {
	if x != nil && x.CreationTimeWindowsEpochMicros != nil {
		return *x.CreationTimeWindowsEpochMicros
	}
	return 0
}

func (x *SavedTabGroupSpecifics) GetUpdateTimeWindowsEpochMicros() int64 {
	if x != nil && x.UpdateTimeWindowsEpochMicros != nil {
		return *x.UpdateTimeWindowsEpochMicros
	}
	return 0
}

func (m *SavedTabGroupSpecifics) GetEntity() isSavedTabGroupSpecifics_Entity {
	if m != nil {
		return m.Entity
	}
	return nil
}

func (x *SavedTabGroupSpecifics) GetGroup() *SavedTabGroup {
	if x, ok := x.GetEntity().(*SavedTabGroupSpecifics_Group); ok {
		return x.Group
	}
	return nil
}

func (x *SavedTabGroupSpecifics) GetTab() *SavedTabGroupTab {
	if x, ok := x.GetEntity().(*SavedTabGroupSpecifics_Tab); ok {
		return x.Tab
	}
	return nil
}

type isSavedTabGroupSpecifics_Entity interface {
	isSavedTabGroupSpecifics_Entity()
}

type SavedTabGroupSpecifics_Group struct {
	Group *SavedTabGroup `protobuf:"bytes,4,opt,name=group,oneof"`
}

type SavedTabGroupSpecifics_Tab struct {
	Tab *SavedTabGroupTab `protobuf:"bytes,5,opt,name=tab,oneof"`
}

func (*SavedTabGroupSpecifics_Group) isSavedTabGroupSpecifics_Entity() {}

func (*SavedTabGroupSpecifics_Tab) isSavedTabGroupSpecifics_Entity() {}

var File_saved_tab_group_specifics_proto protoreflect.FileDescriptor

var file_saved_tab_group_specifics_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x73, 0x61, 0x76, 0x65, 0x64, 0x5f, 0x74, 0x61, 0x62, 0x5f, 0x67, 0x72, 0x6f, 0x75,
	0x70, 0x5f, 0x73, 0x70, 0x65, 0x63, 0x69, 0x66, 0x69, 0x63, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x07, 0x73, 0x79, 0x6e, 0x63, 0x5f, 0x70, 0x62, 0x22, 0xe6, 0x03, 0x0a, 0x0d, 0x53,
	0x61, 0x76, 0x65, 0x64, 0x54, 0x61, 0x62, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x12, 0x1a, 0x0a, 0x08,
	0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08,
	0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x3f,
	0x0a, 0x05, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x29, 0x2e,
	0x73, 0x79, 0x6e, 0x63, 0x5f, 0x70, 0x62, 0x2e, 0x53, 0x61, 0x76, 0x65, 0x64, 0x54, 0x61, 0x62,
	0x47, 0x72, 0x6f, 0x75, 0x70, 0x2e, 0x53, 0x61, 0x76, 0x65, 0x64, 0x54, 0x61, 0x62, 0x47, 0x72,
	0x6f, 0x75, 0x70, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x52, 0x05, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x22,
	0xe1, 0x02, 0x0a, 0x12, 0x53, 0x61, 0x76, 0x65, 0x64, 0x54, 0x61, 0x62, 0x47, 0x72, 0x6f, 0x75,
	0x70, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x12, 0x25, 0x0a, 0x21, 0x53, 0x41, 0x56, 0x45, 0x44, 0x5f,
	0x54, 0x41, 0x42, 0x5f, 0x47, 0x52, 0x4f, 0x55, 0x50, 0x5f, 0x43, 0x4f, 0x4c, 0x4f, 0x52, 0x5f,
	0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x1e, 0x0a,
	0x1a, 0x53, 0x41, 0x56, 0x45, 0x44, 0x5f, 0x54, 0x41, 0x42, 0x5f, 0x47, 0x52, 0x4f, 0x55, 0x50,
	0x5f, 0x43, 0x4f, 0x4c, 0x4f, 0x52, 0x5f, 0x47, 0x52, 0x45, 0x59, 0x10, 0x01, 0x12, 0x1e, 0x0a,
	0x1a, 0x53, 0x41, 0x56, 0x45, 0x44, 0x5f, 0x54, 0x41, 0x42, 0x5f, 0x47, 0x52, 0x4f, 0x55, 0x50,
	0x5f, 0x43, 0x4f, 0x4c, 0x4f, 0x52, 0x5f, 0x42, 0x4c, 0x55, 0x45, 0x10, 0x02, 0x12, 0x1d, 0x0a,
	0x19, 0x53, 0x41, 0x56, 0x45, 0x44, 0x5f, 0x54, 0x41, 0x42, 0x5f, 0x47, 0x52, 0x4f, 0x55, 0x50,
	0x5f, 0x43, 0x4f, 0x4c, 0x4f, 0x52, 0x5f, 0x52, 0x45, 0x44, 0x10, 0x03, 0x12, 0x20, 0x0a, 0x1c,
	0x53, 0x41, 0x56, 0x45, 0x44, 0x5f, 0x54, 0x41, 0x42, 0x5f, 0x47, 0x52, 0x4f, 0x55, 0x50, 0x5f,
	0x43, 0x4f, 0x4c, 0x4f, 0x52, 0x5f, 0x59, 0x45, 0x4c, 0x4c, 0x4f, 0x57, 0x10, 0x04, 0x12, 0x1f,
	0x0a, 0x1b, 0x53, 0x41, 0x56, 0x45, 0x44, 0x5f, 0x54, 0x41, 0x42, 0x5f, 0x47, 0x52, 0x4f, 0x55,
	0x50, 0x5f, 0x43, 0x4f, 0x4c, 0x4f, 0x52, 0x5f, 0x47, 0x52, 0x45, 0x45, 0x4e, 0x10, 0x05, 0x12,
	0x1e, 0x0a, 0x1a, 0x53, 0x41, 0x56, 0x45, 0x44, 0x5f, 0x54, 0x41, 0x42, 0x5f, 0x47, 0x52, 0x4f,
	0x55, 0x50, 0x5f, 0x43, 0x4f, 0x4c, 0x4f, 0x52, 0x5f, 0x50, 0x49, 0x4e, 0x4b, 0x10, 0x06, 0x12,
	0x20, 0x0a, 0x1c, 0x53, 0x41, 0x56, 0x45, 0x44, 0x5f, 0x54, 0x41, 0x42, 0x5f, 0x47, 0x52, 0x4f,
	0x55, 0x50, 0x5f, 0x43, 0x4f, 0x4c, 0x4f, 0x52, 0x5f, 0x50, 0x55, 0x52, 0x50, 0x4c, 0x45, 0x10,
	0x07, 0x12, 0x1e, 0x0a, 0x1a, 0x53, 0x41, 0x56, 0x45, 0x44, 0x5f, 0x54, 0x41, 0x42, 0x5f, 0x47,
	0x52, 0x4f, 0x55, 0x50, 0x5f, 0x43, 0x4f, 0x4c, 0x4f, 0x52, 0x5f, 0x43, 0x59, 0x41, 0x4e, 0x10,
	0x08, 0x12, 0x20, 0x0a, 0x1c, 0x53, 0x41, 0x56, 0x45, 0x44, 0x5f, 0x54, 0x41, 0x42, 0x5f, 0x47,
	0x52, 0x4f, 0x55, 0x50, 0x5f, 0x43, 0x4f, 0x4c, 0x4f, 0x52, 0x5f, 0x4f, 0x52, 0x41, 0x4e, 0x47,
	0x45, 0x10, 0x09, 0x22, 0x75, 0x0a, 0x10, 0x53, 0x61, 0x76, 0x65, 0x64, 0x54, 0x61, 0x62, 0x47,
	0x72, 0x6f, 0x75, 0x70, 0x54, 0x61, 0x62, 0x12, 0x1d, 0x0a, 0x0a, 0x67, 0x72, 0x6f, 0x75, 0x70,
	0x5f, 0x67, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x67, 0x72, 0x6f,
	0x75, 0x70, 0x47, 0x75, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x75, 0x72, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x22, 0xa9, 0x02, 0x0a, 0x16, 0x53,
	0x61, 0x76, 0x65, 0x64, 0x54, 0x61, 0x62, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x53, 0x70, 0x65, 0x63,
	0x69, 0x66, 0x69, 0x63, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x67, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x67, 0x75, 0x69, 0x64, 0x12, 0x4a, 0x0a, 0x22, 0x63, 0x72, 0x65,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x77, 0x69, 0x6e, 0x64, 0x6f,
	0x77, 0x73, 0x5f, 0x65, 0x70, 0x6f, 0x63, 0x68, 0x5f, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x73, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x1e, 0x63, 0x72, 0x65, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54,
	0x69, 0x6d, 0x65, 0x57, 0x69, 0x6e, 0x64, 0x6f, 0x77, 0x73, 0x45, 0x70, 0x6f, 0x63, 0x68, 0x4d,
	0x69, 0x63, 0x72, 0x6f, 0x73, 0x12, 0x46, 0x0a, 0x20, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x5f,
	0x74, 0x69, 0x6d, 0x65, 0x5f, 0x77, 0x69, 0x6e, 0x64, 0x6f, 0x77, 0x73, 0x5f, 0x65, 0x70, 0x6f,
	0x63, 0x68, 0x5f, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x1c, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x57, 0x69, 0x6e, 0x64, 0x6f,
	0x77, 0x73, 0x45, 0x70, 0x6f, 0x63, 0x68, 0x4d, 0x69, 0x63, 0x72, 0x6f, 0x73, 0x12, 0x2e, 0x0a,
	0x05, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x73,
	0x79, 0x6e, 0x63, 0x5f, 0x70, 0x62, 0x2e, 0x53, 0x61, 0x76, 0x65, 0x64, 0x54, 0x61, 0x62, 0x47,
	0x72, 0x6f, 0x75, 0x70, 0x48, 0x00, 0x52, 0x05, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x12, 0x2d, 0x0a,
	0x03, 0x74, 0x61, 0x62, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x73, 0x79, 0x6e,
	0x63, 0x5f, 0x70, 0x62, 0x2e, 0x53, 0x61, 0x76, 0x65, 0x64, 0x54, 0x61, 0x62, 0x47, 0x72, 0x6f,
	0x75, 0x70, 0x54, 0x61, 0x62, 0x48, 0x00, 0x52, 0x03, 0x74, 0x61, 0x62, 0x42, 0x08, 0x0a, 0x06,
	0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x42, 0x36, 0x0a, 0x25, 0x6f, 0x72, 0x67, 0x2e, 0x63, 0x68,
	0x72, 0x6f, 0x6d, 0x69, 0x75, 0x6d, 0x2e, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74,
	0x73, 0x2e, 0x73, 0x79, 0x6e, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x48,
	0x03, 0x50, 0x01, 0x5a, 0x09, 0x2e, 0x2f, 0x73, 0x79, 0x6e, 0x63, 0x5f, 0x70, 0x62,
}

var (
	file_saved_tab_group_specifics_proto_rawDescOnce sync.Once
	file_saved_tab_group_specifics_proto_rawDescData = file_saved_tab_group_specifics_proto_rawDesc
)

func file_saved_tab_group_specifics_proto_rawDescGZIP() []byte {
	file_saved_tab_group_specifics_proto_rawDescOnce.Do(func() {
		file_saved_tab_group_specifics_proto_rawDescData = protoimpl.X.CompressGZIP(file_saved_tab_group_specifics_proto_rawDescData)
	})
	return file_saved_tab_group_specifics_proto_rawDescData
}

var file_saved_tab_group_specifics_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_saved_tab_group_specifics_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_saved_tab_group_specifics_proto_goTypes = []interface{}{
	(SavedTabGroup_SavedTabGroupColor)(0), // 0: sync_pb.SavedTabGroup.SavedTabGroupColor
	(*SavedTabGroup)(nil),                 // 1: sync_pb.SavedTabGroup
	(*SavedTabGroupTab)(nil),              // 2: sync_pb.SavedTabGroupTab
	(*SavedTabGroupSpecifics)(nil),        // 3: sync_pb.SavedTabGroupSpecifics
}
var file_saved_tab_group_specifics_proto_depIdxs = []int32{
	0, // 0: sync_pb.SavedTabGroup.color:type_name -> sync_pb.SavedTabGroup.SavedTabGroupColor
	1, // 1: sync_pb.SavedTabGroupSpecifics.group:type_name -> sync_pb.SavedTabGroup
	2, // 2: sync_pb.SavedTabGroupSpecifics.tab:type_name -> sync_pb.SavedTabGroupTab
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_saved_tab_group_specifics_proto_init() }
func file_saved_tab_group_specifics_proto_init() {
	if File_saved_tab_group_specifics_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_saved_tab_group_specifics_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SavedTabGroup); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_saved_tab_group_specifics_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SavedTabGroupTab); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_saved_tab_group_specifics_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SavedTabGroupSpecifics); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_saved_tab_group_specifics_proto_msgTypes[2].OneofWrappers = []interface{}{
		(*SavedTabGroupSpecifics_Group)(nil),
		(*SavedTabGroupSpecifics_Tab)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_saved_tab_group_specifics_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_saved_tab_group_specifics_proto_goTypes,
		DependencyIndexes: file_saved_tab_group_specifics_proto_depIdxs,
		EnumInfos:         file_saved_tab_group_specifics_proto_enumTypes,
		MessageInfos:      file_saved_tab_group_specifics_proto_msgTypes,
	}.Build()
	File_saved_tab_group_specifics_proto = out.File
	file_saved_tab_group_specifics_proto_rawDesc = nil
	file_saved_tab_group_specifics_proto_goTypes = nil
	file_saved_tab_group_specifics_proto_depIdxs = nil
}
