// Code generated by protoc-gen-go. DO NOT EDIT.
// source: send_tab_to_self_specifics.proto

package sync_pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Send Tab To Self list entry. This proto contains the fields synced to send
// a url across devices.
type SendTabToSelfSpecifics struct {
	// A random unique identifier for each shared tab.
	// Required.
	Guid *string `protobuf:"bytes,5,opt,name=guid" json:"guid,omitempty"`
	// The name of the tab being shared.
	Title *string `protobuf:"bytes,1,opt,name=title" json:"title,omitempty"`
	// The URL of the tab being shared.
	// Required.
	Url *string `protobuf:"bytes,2,opt,name=url" json:"url,omitempty"`
	// The time the tab was shared as measured by the client in microseconds since
	// the windows epoch.
	SharedTimeUsec *int64 `protobuf:"varint,3,opt,name=shared_time_usec,json=sharedTimeUsec" json:"shared_time_usec,omitempty"`
	// The time the tab was navigated to as measured by the client in microseconds
	// since the windows epoch.
	NavigationTimeUsec *int64 `protobuf:"varint,6,opt,name=navigation_time_usec,json=navigationTimeUsec" json:"navigation_time_usec,omitempty"`
	// A non-unique but human readable name to describe this client, used in UI.
	DeviceName *string `protobuf:"bytes,4,opt,name=device_name,json=deviceName" json:"device_name,omitempty"`
	// The stable Device_id of the device that this tab was shared with.
	// Required.
	TargetDeviceSyncCacheGuid *string `protobuf:"bytes,7,opt,name=target_device_sync_cache_guid,json=targetDeviceSyncCacheGuid" json:"target_device_sync_cache_guid,omitempty"`
	// A boolean to designate if the shared tab been opened on the target device.
	Opened *bool `protobuf:"varint,8,opt,name=opened" json:"opened,omitempty"`
	// Whether the notification for this proto been dismissed.
	NotificationDismissed *bool    `protobuf:"varint,9,opt,name=notification_dismissed,json=notificationDismissed" json:"notification_dismissed,omitempty"`
	XXX_NoUnkeyedLiteral  struct{} `json:"-"`
	XXX_unrecognized      []byte   `json:"-"`
	XXX_sizecache         int32    `json:"-"`
}

func (m *SendTabToSelfSpecifics) Reset()         { *m = SendTabToSelfSpecifics{} }
func (m *SendTabToSelfSpecifics) String() string { return proto.CompactTextString(m) }
func (*SendTabToSelfSpecifics) ProtoMessage()    {}
func (*SendTabToSelfSpecifics) Descriptor() ([]byte, []int) {
	return fileDescriptor_808e01deb718faf8, []int{0}
}

func (m *SendTabToSelfSpecifics) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendTabToSelfSpecifics.Unmarshal(m, b)
}
func (m *SendTabToSelfSpecifics) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendTabToSelfSpecifics.Marshal(b, m, deterministic)
}
func (m *SendTabToSelfSpecifics) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendTabToSelfSpecifics.Merge(m, src)
}
func (m *SendTabToSelfSpecifics) XXX_Size() int {
	return xxx_messageInfo_SendTabToSelfSpecifics.Size(m)
}
func (m *SendTabToSelfSpecifics) XXX_DiscardUnknown() {
	xxx_messageInfo_SendTabToSelfSpecifics.DiscardUnknown(m)
}

var xxx_messageInfo_SendTabToSelfSpecifics proto.InternalMessageInfo

func (m *SendTabToSelfSpecifics) GetGuid() string {
	if m != nil && m.Guid != nil {
		return *m.Guid
	}
	return ""
}

func (m *SendTabToSelfSpecifics) GetTitle() string {
	if m != nil && m.Title != nil {
		return *m.Title
	}
	return ""
}

func (m *SendTabToSelfSpecifics) GetUrl() string {
	if m != nil && m.Url != nil {
		return *m.Url
	}
	return ""
}

func (m *SendTabToSelfSpecifics) GetSharedTimeUsec() int64 {
	if m != nil && m.SharedTimeUsec != nil {
		return *m.SharedTimeUsec
	}
	return 0
}

func (m *SendTabToSelfSpecifics) GetNavigationTimeUsec() int64 {
	if m != nil && m.NavigationTimeUsec != nil {
		return *m.NavigationTimeUsec
	}
	return 0
}

func (m *SendTabToSelfSpecifics) GetDeviceName() string {
	if m != nil && m.DeviceName != nil {
		return *m.DeviceName
	}
	return ""
}

func (m *SendTabToSelfSpecifics) GetTargetDeviceSyncCacheGuid() string {
	if m != nil && m.TargetDeviceSyncCacheGuid != nil {
		return *m.TargetDeviceSyncCacheGuid
	}
	return ""
}

func (m *SendTabToSelfSpecifics) GetOpened() bool {
	if m != nil && m.Opened != nil {
		return *m.Opened
	}
	return false
}

func (m *SendTabToSelfSpecifics) GetNotificationDismissed() bool {
	if m != nil && m.NotificationDismissed != nil {
		return *m.NotificationDismissed
	}
	return false
}

func init() {
	proto.RegisterType((*SendTabToSelfSpecifics)(nil), "sync_pb.SendTabToSelfSpecifics")
}

func init() {
	proto.RegisterFile("send_tab_to_self_specifics.proto", fileDescriptor_808e01deb718faf8)
}

var fileDescriptor_808e01deb718faf8 = []byte{
	// 315 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x91, 0x4f, 0x4b, 0x33, 0x31,
	0x10, 0xc6, 0xd9, 0x6e, 0xff, 0xce, 0x0b, 0x2f, 0x25, 0xd4, 0x12, 0x0f, 0xe2, 0x22, 0x08, 0x0b,
	0xc2, 0xe2, 0xc5, 0xbb, 0x68, 0x41, 0x4f, 0x22, 0xdd, 0x7a, 0x0e, 0x69, 0x32, 0xdd, 0x06, 0x36,
	0xc9, 0xb2, 0xc9, 0x16, 0xfa, 0x75, 0xfd, 0x24, 0xb2, 0x49, 0xab, 0xbd, 0xcd, 0x3c, 0xcf, 0x6f,
	0xc8, 0x3c, 0x19, 0xc8, 0x1c, 0x1a, 0xc9, 0x3c, 0xdf, 0x32, 0x6f, 0x99, 0xc3, 0x7a, 0xc7, 0x5c,
	0x83, 0x42, 0xed, 0x94, 0x70, 0x45, 0xd3, 0x5a, 0x6f, 0xc9, 0xc4, 0x1d, 0x8d, 0x60, 0xcd, 0xf6,
	0xee, 0x7b, 0x00, 0xcb, 0x12, 0x8d, 0xdc, 0xf0, 0xed, 0xc6, 0x96, 0x58, 0xef, 0xca, 0x33, 0x49,
	0x08, 0x0c, 0xab, 0x4e, 0x49, 0x3a, 0xca, 0x92, 0x7c, 0xb6, 0x0e, 0x35, 0x59, 0xc0, 0xc8, 0x2b,
	0x5f, 0x23, 0x4d, 0x82, 0x18, 0x1b, 0x32, 0x87, 0xb4, 0x6b, 0x6b, 0x3a, 0x08, 0x5a, 0x5f, 0x92,
	0x1c, 0xe6, 0x6e, 0xcf, 0x5b, 0x94, 0xcc, 0x2b, 0x8d, 0xac, 0x73, 0x28, 0x68, 0x9a, 0x25, 0x79,
	0xba, 0xfe, 0x1f, 0xf5, 0x8d, 0xd2, 0xf8, 0xe5, 0x50, 0x90, 0x47, 0x58, 0x18, 0x7e, 0x50, 0x15,
	0xf7, 0xca, 0x9a, 0x0b, 0x7a, 0x1c, 0x68, 0xf2, 0xe7, 0xfd, 0x4e, 0xdc, 0xc2, 0x3f, 0x89, 0x07,
	0x25, 0x90, 0x19, 0xae, 0x91, 0x0e, 0xc3, 0xab, 0x10, 0xa5, 0x0f, 0xae, 0x91, 0x3c, 0xc3, 0x8d,
	0xe7, 0x6d, 0x85, 0x9e, 0x9d, 0xb8, 0x10, 0x56, 0x70, 0xb1, 0x47, 0x16, 0x12, 0x4d, 0xc2, 0xc8,
	0x75, 0x84, 0x56, 0x81, 0x29, 0x8f, 0x46, 0xbc, 0xf6, 0xc4, 0x5b, 0x1f, 0x73, 0x09, 0x63, 0xdb,
	0xa0, 0x41, 0x49, 0xa7, 0x59, 0x92, 0x4f, 0xd7, 0xa7, 0x8e, 0x3c, 0xc1, 0xd2, 0x58, 0xdf, 0x7f,
	0x4f, 0x5c, 0x57, 0x2a, 0xa7, 0x95, 0x73, 0x28, 0xe9, 0x2c, 0x70, 0x57, 0x97, 0xee, 0xea, 0x6c,
	0xbe, 0x3c, 0xc0, 0xbd, 0x6d, 0xab, 0x42, 0xec, 0x5b, 0xab, 0x55, 0xa7, 0x0b, 0x61, 0x75, 0x63,
	0x0d, 0x1a, 0xef, 0x8a, 0x7e, 0xb5, 0x78, 0x13, 0x61, 0xeb, 0xf7, 0xf4, 0x33, 0xf9, 0x09, 0x00,
	0x00, 0xff, 0xff, 0x9e, 0xd5, 0x75, 0x25, 0xbd, 0x01, 0x00, 0x00,
}
