// Code generated by protoc-gen-go. DO NOT EDIT.
// source: bookmark_specifics.proto

package sync_pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Corresponds to a single meta info key/value pair for a bookmark node.
type MetaInfo struct {
	Key                  *string  `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	Value                *string  `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MetaInfo) Reset()         { *m = MetaInfo{} }
func (m *MetaInfo) String() string { return proto.CompactTextString(m) }
func (*MetaInfo) ProtoMessage()    {}
func (*MetaInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_18b074d681efa94e, []int{0}
}

func (m *MetaInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MetaInfo.Unmarshal(m, b)
}
func (m *MetaInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MetaInfo.Marshal(b, m, deterministic)
}
func (m *MetaInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MetaInfo.Merge(m, src)
}
func (m *MetaInfo) XXX_Size() int {
	return xxx_messageInfo_MetaInfo.Size(m)
}
func (m *MetaInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_MetaInfo.DiscardUnknown(m)
}

var xxx_messageInfo_MetaInfo proto.InternalMessageInfo

func (m *MetaInfo) GetKey() string {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return ""
}

func (m *MetaInfo) GetValue() string {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return ""
}

// Properties of bookmark sync objects.
type BookmarkSpecifics struct {
	Url     *string `protobuf:"bytes,1,opt,name=url" json:"url,omitempty"`
	Favicon []byte  `protobuf:"bytes,2,opt,name=favicon" json:"favicon,omitempty"`
	Title   *string `protobuf:"bytes,3,opt,name=title" json:"title,omitempty"`
	// Corresponds to BookmarkNode::date_added() represented as microseconds since
	// the Windows epoch.
	CreationTimeUs *int64      `protobuf:"varint,4,opt,name=creation_time_us,json=creationTimeUs" json:"creation_time_us,omitempty"`
	IconUrl        *string     `protobuf:"bytes,5,opt,name=icon_url,json=iconUrl" json:"icon_url,omitempty"`
	MetaInfo       []*MetaInfo `protobuf:"bytes,6,rep,name=meta_info,json=metaInfo" json:"meta_info,omitempty"`
	// Introduced in M78. If not present, originator_client_item_id is interpreted
	// as GUID as long as it is of the valid format. Otherwise, field is either
	// ignored or overwritten locally.
	Guid                 *string  `protobuf:"bytes,7,opt,name=guid" json:"guid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BookmarkSpecifics) Reset()         { *m = BookmarkSpecifics{} }
func (m *BookmarkSpecifics) String() string { return proto.CompactTextString(m) }
func (*BookmarkSpecifics) ProtoMessage()    {}
func (*BookmarkSpecifics) Descriptor() ([]byte, []int) {
	return fileDescriptor_18b074d681efa94e, []int{1}
}

func (m *BookmarkSpecifics) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BookmarkSpecifics.Unmarshal(m, b)
}
func (m *BookmarkSpecifics) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BookmarkSpecifics.Marshal(b, m, deterministic)
}
func (m *BookmarkSpecifics) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BookmarkSpecifics.Merge(m, src)
}
func (m *BookmarkSpecifics) XXX_Size() int {
	return xxx_messageInfo_BookmarkSpecifics.Size(m)
}
func (m *BookmarkSpecifics) XXX_DiscardUnknown() {
	xxx_messageInfo_BookmarkSpecifics.DiscardUnknown(m)
}

var xxx_messageInfo_BookmarkSpecifics proto.InternalMessageInfo

func (m *BookmarkSpecifics) GetUrl() string {
	if m != nil && m.Url != nil {
		return *m.Url
	}
	return ""
}

func (m *BookmarkSpecifics) GetFavicon() []byte {
	if m != nil {
		return m.Favicon
	}
	return nil
}

func (m *BookmarkSpecifics) GetTitle() string {
	if m != nil && m.Title != nil {
		return *m.Title
	}
	return ""
}

func (m *BookmarkSpecifics) GetCreationTimeUs() int64 {
	if m != nil && m.CreationTimeUs != nil {
		return *m.CreationTimeUs
	}
	return 0
}

func (m *BookmarkSpecifics) GetIconUrl() string {
	if m != nil && m.IconUrl != nil {
		return *m.IconUrl
	}
	return ""
}

func (m *BookmarkSpecifics) GetMetaInfo() []*MetaInfo {
	if m != nil {
		return m.MetaInfo
	}
	return nil
}

func (m *BookmarkSpecifics) GetGuid() string {
	if m != nil && m.Guid != nil {
		return *m.Guid
	}
	return ""
}

func init() {
	proto.RegisterType((*MetaInfo)(nil), "sync_pb.MetaInfo")
	proto.RegisterType((*BookmarkSpecifics)(nil), "sync_pb.BookmarkSpecifics")
}

func init() {
	proto.RegisterFile("bookmark_specifics.proto", fileDescriptor_18b074d681efa94e)
}

var fileDescriptor_18b074d681efa94e = []byte{
	// 268 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x34, 0x90, 0xcd, 0x6a, 0x33, 0x21,
	0x18, 0x85, 0x99, 0x6f, 0x92, 0x6f, 0x12, 0x5b, 0x4a, 0x22, 0x5d, 0xd8, 0xdd, 0x10, 0x28, 0x0c,
	0x14, 0x5c, 0xe4, 0x12, 0xb2, 0x6a, 0x17, 0x85, 0x32, 0x6d, 0xd6, 0x62, 0xac, 0x93, 0xca, 0xa8,
	0xef, 0xe0, 0x4f, 0x20, 0x37, 0xdb, 0x6b, 0x29, 0x3a, 0x71, 0xf7, 0x3e, 0x07, 0xce, 0x23, 0x47,
	0x44, 0x4e, 0x00, 0xa3, 0xe1, 0x6e, 0x64, 0x7e, 0x92, 0x42, 0x0d, 0x4a, 0x78, 0x3a, 0x39, 0x08,
	0x80, 0x1b, 0x7f, 0xb5, 0x82, 0x4d, 0xa7, 0xdd, 0x1e, 0xad, 0xde, 0x65, 0xe0, 0x6f, 0x76, 0x00,
	0xbc, 0x41, 0xf5, 0x28, 0xaf, 0xa4, 0x6a, 0xab, 0x6e, 0xdd, 0xa7, 0x13, 0x3f, 0xa2, 0xe5, 0x85,
	0xeb, 0x28, 0xc9, 0xbf, 0x9c, 0xcd, 0xb0, 0xfb, 0xad, 0xd0, 0xf6, 0x70, 0x33, 0x7f, 0x16, 0x71,
	0x6a, 0x47, 0xa7, 0x4b, 0x3b, 0x3a, 0x8d, 0x09, 0x6a, 0x06, 0x7e, 0x51, 0x02, 0x6c, 0xee, 0xdf,
	0xf7, 0x05, 0x93, 0x37, 0xa8, 0xa0, 0x25, 0xa9, 0x67, 0x6f, 0x06, 0xdc, 0xa1, 0x8d, 0x70, 0x92,
	0x07, 0x05, 0x96, 0x05, 0x65, 0x24, 0x8b, 0x9e, 0x2c, 0xda, 0xaa, 0xab, 0xfb, 0x87, 0x92, 0x7f,
	0x29, 0x23, 0x8f, 0x1e, 0x3f, 0xa1, 0x55, 0xf2, 0xb0, 0xf4, 0xe0, 0x32, 0x2b, 0x9a, 0xc4, 0x47,
	0xa7, 0x31, 0x45, 0x6b, 0x23, 0x03, 0x67, 0xca, 0x0e, 0x40, 0xfe, 0xb7, 0x75, 0x77, 0xb7, 0xdf,
	0xd2, 0xdb, 0x5a, 0x5a, 0xa6, 0xf6, 0x2b, 0x53, 0x46, 0x63, 0xb4, 0x38, 0x47, 0xf5, 0x4d, 0x9a,
	0xac, 0xc9, 0xf7, 0xe1, 0x05, 0x3d, 0x83, 0x3b, 0x53, 0xf1, 0xe3, 0xc0, 0xa8, 0x68, 0xa8, 0x00,
	0x33, 0x81, 0x95, 0x36, 0xf8, 0x6c, 0x9a, 0xff, 0x50, 0x80, 0x7e, 0xad, 0x3f, 0xaa, 0xbf, 0x00,
	0x00, 0x00, 0xff, 0xff, 0x10, 0x96, 0x3e, 0x30, 0x65, 0x01, 0x00, 0x00,
}
