// Code generated by protoc-gen-go. DO NOT EDIT.
// source: history_delete_directive_specifics.proto

package sync_pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Properties of history delete directive sync objects.
type HistoryDeleteDirectiveSpecifics struct {
	// Exactly one of the fields below must be filled in.  Otherwise, this
	// delete directive must be ignored.
	GlobalIdDirective    *GlobalIdDirective  `protobuf:"bytes,1,opt,name=global_id_directive,json=globalIdDirective" json:"global_id_directive,omitempty"`
	TimeRangeDirective   *TimeRangeDirective `protobuf:"bytes,2,opt,name=time_range_directive,json=timeRangeDirective" json:"time_range_directive,omitempty"`
	UrlDirective         *UrlDirective       `protobuf:"bytes,3,opt,name=url_directive,json=urlDirective" json:"url_directive,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *HistoryDeleteDirectiveSpecifics) Reset()         { *m = HistoryDeleteDirectiveSpecifics{} }
func (m *HistoryDeleteDirectiveSpecifics) String() string { return proto.CompactTextString(m) }
func (*HistoryDeleteDirectiveSpecifics) ProtoMessage()    {}
func (*HistoryDeleteDirectiveSpecifics) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fb8aac0861bbe8a, []int{0}
}

func (m *HistoryDeleteDirectiveSpecifics) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HistoryDeleteDirectiveSpecifics.Unmarshal(m, b)
}
func (m *HistoryDeleteDirectiveSpecifics) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HistoryDeleteDirectiveSpecifics.Marshal(b, m, deterministic)
}
func (m *HistoryDeleteDirectiveSpecifics) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HistoryDeleteDirectiveSpecifics.Merge(m, src)
}
func (m *HistoryDeleteDirectiveSpecifics) XXX_Size() int {
	return xxx_messageInfo_HistoryDeleteDirectiveSpecifics.Size(m)
}
func (m *HistoryDeleteDirectiveSpecifics) XXX_DiscardUnknown() {
	xxx_messageInfo_HistoryDeleteDirectiveSpecifics.DiscardUnknown(m)
}

var xxx_messageInfo_HistoryDeleteDirectiveSpecifics proto.InternalMessageInfo

func (m *HistoryDeleteDirectiveSpecifics) GetGlobalIdDirective() *GlobalIdDirective {
	if m != nil {
		return m.GlobalIdDirective
	}
	return nil
}

func (m *HistoryDeleteDirectiveSpecifics) GetTimeRangeDirective() *TimeRangeDirective {
	if m != nil {
		return m.TimeRangeDirective
	}
	return nil
}

func (m *HistoryDeleteDirectiveSpecifics) GetUrlDirective() *UrlDirective {
	if m != nil {
		return m.UrlDirective
	}
	return nil
}

type GlobalIdDirective struct {
	// The global IDs of the navigations to delete.
	GlobalId []int64 `protobuf:"varint,1,rep,name=global_id,json=globalId" json:"global_id,omitempty"`
	// Time range for searching for navigations to delete. Client should delete
	// all navigations to a URL between [start_time_usec, end_time_usec]
	// if one of them matches a |global_id|.
	StartTimeUsec        *int64   `protobuf:"varint,2,opt,name=start_time_usec,json=startTimeUsec" json:"start_time_usec,omitempty"`
	EndTimeUsec          *int64   `protobuf:"varint,3,opt,name=end_time_usec,json=endTimeUsec" json:"end_time_usec,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GlobalIdDirective) Reset()         { *m = GlobalIdDirective{} }
func (m *GlobalIdDirective) String() string { return proto.CompactTextString(m) }
func (*GlobalIdDirective) ProtoMessage()    {}
func (*GlobalIdDirective) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fb8aac0861bbe8a, []int{1}
}

func (m *GlobalIdDirective) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GlobalIdDirective.Unmarshal(m, b)
}
func (m *GlobalIdDirective) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GlobalIdDirective.Marshal(b, m, deterministic)
}
func (m *GlobalIdDirective) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GlobalIdDirective.Merge(m, src)
}
func (m *GlobalIdDirective) XXX_Size() int {
	return xxx_messageInfo_GlobalIdDirective.Size(m)
}
func (m *GlobalIdDirective) XXX_DiscardUnknown() {
	xxx_messageInfo_GlobalIdDirective.DiscardUnknown(m)
}

var xxx_messageInfo_GlobalIdDirective proto.InternalMessageInfo

func (m *GlobalIdDirective) GetGlobalId() []int64 {
	if m != nil {
		return m.GlobalId
	}
	return nil
}

func (m *GlobalIdDirective) GetStartTimeUsec() int64 {
	if m != nil && m.StartTimeUsec != nil {
		return *m.StartTimeUsec
	}
	return 0
}

func (m *GlobalIdDirective) GetEndTimeUsec() int64 {
	if m != nil && m.EndTimeUsec != nil {
		return *m.EndTimeUsec
	}
	return 0
}

type TimeRangeDirective struct {
	// The time on or after which entries must be deleted.
	StartTimeUsec *int64 `protobuf:"varint,1,opt,name=start_time_usec,json=startTimeUsec" json:"start_time_usec,omitempty"`
	// The time on or before which entries must be deleted.
	EndTimeUsec          *int64   `protobuf:"varint,2,opt,name=end_time_usec,json=endTimeUsec" json:"end_time_usec,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TimeRangeDirective) Reset()         { *m = TimeRangeDirective{} }
func (m *TimeRangeDirective) String() string { return proto.CompactTextString(m) }
func (*TimeRangeDirective) ProtoMessage()    {}
func (*TimeRangeDirective) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fb8aac0861bbe8a, []int{2}
}

func (m *TimeRangeDirective) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TimeRangeDirective.Unmarshal(m, b)
}
func (m *TimeRangeDirective) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TimeRangeDirective.Marshal(b, m, deterministic)
}
func (m *TimeRangeDirective) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TimeRangeDirective.Merge(m, src)
}
func (m *TimeRangeDirective) XXX_Size() int {
	return xxx_messageInfo_TimeRangeDirective.Size(m)
}
func (m *TimeRangeDirective) XXX_DiscardUnknown() {
	xxx_messageInfo_TimeRangeDirective.DiscardUnknown(m)
}

var xxx_messageInfo_TimeRangeDirective proto.InternalMessageInfo

func (m *TimeRangeDirective) GetStartTimeUsec() int64 {
	if m != nil && m.StartTimeUsec != nil {
		return *m.StartTimeUsec
	}
	return 0
}

func (m *TimeRangeDirective) GetEndTimeUsec() int64 {
	if m != nil && m.EndTimeUsec != nil {
		return *m.EndTimeUsec
	}
	return 0
}

type UrlDirective struct {
	// The URL that should be removed from history.
	Url *string `protobuf:"bytes,1,opt,name=url" json:"url,omitempty"`
	// The time on or before which entries must be deleted.
	// In microseconds since the Unix epoch.
	EndTimeUsec          *int64   `protobuf:"varint,2,opt,name=end_time_usec,json=endTimeUsec" json:"end_time_usec,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UrlDirective) Reset()         { *m = UrlDirective{} }
func (m *UrlDirective) String() string { return proto.CompactTextString(m) }
func (*UrlDirective) ProtoMessage()    {}
func (*UrlDirective) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fb8aac0861bbe8a, []int{3}
}

func (m *UrlDirective) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UrlDirective.Unmarshal(m, b)
}
func (m *UrlDirective) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UrlDirective.Marshal(b, m, deterministic)
}
func (m *UrlDirective) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UrlDirective.Merge(m, src)
}
func (m *UrlDirective) XXX_Size() int {
	return xxx_messageInfo_UrlDirective.Size(m)
}
func (m *UrlDirective) XXX_DiscardUnknown() {
	xxx_messageInfo_UrlDirective.DiscardUnknown(m)
}

var xxx_messageInfo_UrlDirective proto.InternalMessageInfo

func (m *UrlDirective) GetUrl() string {
	if m != nil && m.Url != nil {
		return *m.Url
	}
	return ""
}

func (m *UrlDirective) GetEndTimeUsec() int64 {
	if m != nil && m.EndTimeUsec != nil {
		return *m.EndTimeUsec
	}
	return 0
}

func init() {
	proto.RegisterType((*HistoryDeleteDirectiveSpecifics)(nil), "sync_pb.HistoryDeleteDirectiveSpecifics")
	proto.RegisterType((*GlobalIdDirective)(nil), "sync_pb.GlobalIdDirective")
	proto.RegisterType((*TimeRangeDirective)(nil), "sync_pb.TimeRangeDirective")
	proto.RegisterType((*UrlDirective)(nil), "sync_pb.UrlDirective")
}

func init() {
	proto.RegisterFile("history_delete_directive_specifics.proto", fileDescriptor_2fb8aac0861bbe8a)
}

var fileDescriptor_2fb8aac0861bbe8a = []byte{
	// 320 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0xc1, 0x4b, 0xf3, 0x30,
	0x18, 0xc6, 0xe9, 0x72, 0xf8, 0xbe, 0xbd, 0xdb, 0xd0, 0x45, 0x85, 0xe1, 0x0e, 0x8e, 0x82, 0x32,
	0x10, 0x7a, 0xf0, 0xe8, 0x51, 0x06, 0x4e, 0x41, 0x90, 0xea, 0xce, 0x71, 0x4b, 0x5e, 0xbb, 0x40,
	0x9a, 0x94, 0x24, 0x15, 0x06, 0xfe, 0xe1, 0x1e, 0x65, 0x99, 0xed, 0x8a, 0xf5, 0xb0, 0x5b, 0xf2,
	0xf2, 0x3c, 0xbf, 0xf7, 0x79, 0x42, 0x60, 0xba, 0x96, 0xce, 0x1b, 0xbb, 0x61, 0x02, 0x15, 0x7a,
	0x64, 0x42, 0x5a, 0xe4, 0x5e, 0x7e, 0x20, 0x73, 0x05, 0x72, 0xf9, 0x2e, 0xb9, 0x4b, 0x0a, 0x6b,
	0xbc, 0xa1, 0xff, 0xdc, 0x46, 0x73, 0x56, 0xac, 0xe2, 0xaf, 0x08, 0x2e, 0xe6, 0x3b, 0xd7, 0x2c,
	0x98, 0x66, 0x95, 0xe7, 0xa5, 0xb2, 0xd0, 0x47, 0x38, 0xc9, 0x94, 0x59, 0x2d, 0x15, 0x93, 0x62,
	0xcf, 0x1c, 0x45, 0x93, 0x68, 0xda, 0xbb, 0x39, 0x4f, 0x7e, 0x50, 0xc9, 0x7d, 0xd0, 0x3c, 0x88,
	0x9a, 0x90, 0x0e, 0xb3, 0xdf, 0x23, 0xfa, 0x04, 0xa7, 0x5e, 0xe6, 0xc8, 0xec, 0x52, 0x67, 0x8d,
	0x80, 0xa3, 0x4e, 0x80, 0x8d, 0x6b, 0xd8, 0xab, 0xcc, 0x31, 0xdd, 0x6a, 0xf6, 0x34, 0xea, 0x5b,
	0x33, 0x7a, 0x0b, 0x83, 0xd2, 0xaa, 0x06, 0x87, 0x04, 0xce, 0x59, 0xcd, 0x59, 0x58, 0xb5, 0x27,
	0xf4, 0xcb, 0xc6, 0x2d, 0xfe, 0x84, 0x61, 0x2b, 0x32, 0x1d, 0x43, 0xb7, 0xee, 0x3a, 0x8a, 0x26,
	0x64, 0x4a, 0xd2, 0xff, 0x55, 0x0b, 0x7a, 0x05, 0x47, 0xce, 0x2f, 0xad, 0x67, 0xa1, 0x42, 0xe9,
	0x90, 0x87, 0xdc, 0x24, 0x1d, 0x84, 0xf1, 0x36, 0xf3, 0xc2, 0x21, 0xa7, 0x31, 0x0c, 0x50, 0x8b,
	0x86, 0x8a, 0x04, 0x55, 0x0f, 0xb5, 0xa8, 0x34, 0xf1, 0x1b, 0xd0, 0x76, 0xc7, 0xbf, 0x36, 0x44,
	0x07, 0x6d, 0xe8, 0xb4, 0x37, 0xcc, 0xa0, 0xdf, 0x6c, 0x4f, 0x8f, 0x81, 0x94, 0x56, 0x05, 0x5e,
	0x37, 0xdd, 0x1e, 0x0f, 0xa1, 0xdc, 0x5d, 0xc3, 0xa5, 0xb1, 0x59, 0xc2, 0xd7, 0xd6, 0xe4, 0xb2,
	0xcc, 0x13, 0x6e, 0xf2, 0xc2, 0x68, 0xd4, 0xde, 0x85, 0x37, 0xde, 0xfd, 0x27, 0x6e, 0xd4, 0x9c,
	0x3c, 0x47, 0xdf, 0x01, 0x00, 0x00, 0xff, 0xff, 0xdf, 0x5e, 0xdc, 0x97, 0x81, 0x02, 0x00, 0x00,
}
