// Code generated by protoc-gen-go. DO NOT EDIT.
// source: loopback_server.proto

package sync_pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Entity type mapping to one of the subclasses of LoopbackServerEntity.
type LoopbackServerEntity_Type int32

const (
	LoopbackServerEntity_UNKNOWN   LoopbackServerEntity_Type = 0
	LoopbackServerEntity_BOOKMARK  LoopbackServerEntity_Type = 1
	LoopbackServerEntity_PERMANENT LoopbackServerEntity_Type = 2
	LoopbackServerEntity_TOMBSTONE LoopbackServerEntity_Type = 3
	LoopbackServerEntity_UNIQUE    LoopbackServerEntity_Type = 4
)

var LoopbackServerEntity_Type_name = map[int32]string{
	0: "UNKNOWN",
	1: "BOOKMARK",
	2: "PERMANENT",
	3: "TOMBSTONE",
	4: "UNIQUE",
}

var LoopbackServerEntity_Type_value = map[string]int32{
	"UNKNOWN":   0,
	"BOOKMARK":  1,
	"PERMANENT": 2,
	"TOMBSTONE": 3,
	"UNIQUE":    4,
}

func (x LoopbackServerEntity_Type) Enum() *LoopbackServerEntity_Type {
	p := new(LoopbackServerEntity_Type)
	*p = x
	return p
}

func (x LoopbackServerEntity_Type) String() string {
	return proto.EnumName(LoopbackServerEntity_Type_name, int32(x))
}

func (x *LoopbackServerEntity_Type) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(LoopbackServerEntity_Type_value, data, "LoopbackServerEntity_Type")
	if err != nil {
		return err
	}
	*x = LoopbackServerEntity_Type(value)
	return nil
}

func (LoopbackServerEntity_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a041143cb25b822d, []int{0, 0}
}

// Serialization of the LoopbackServerEntity and its ancestors.
type LoopbackServerEntity struct {
	Type                 *LoopbackServerEntity_Type `protobuf:"varint,1,opt,name=type,enum=sync_pb.LoopbackServerEntity_Type" json:"type,omitempty"`
	Entity               *SyncEntity                `protobuf:"bytes,2,opt,name=entity" json:"entity,omitempty"`
	ModelType            *int64                     `protobuf:"varint,3,opt,name=model_type,json=modelType" json:"model_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *LoopbackServerEntity) Reset()         { *m = LoopbackServerEntity{} }
func (m *LoopbackServerEntity) String() string { return proto.CompactTextString(m) }
func (*LoopbackServerEntity) ProtoMessage()    {}
func (*LoopbackServerEntity) Descriptor() ([]byte, []int) {
	return fileDescriptor_a041143cb25b822d, []int{0}
}

func (m *LoopbackServerEntity) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoopbackServerEntity.Unmarshal(m, b)
}
func (m *LoopbackServerEntity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoopbackServerEntity.Marshal(b, m, deterministic)
}
func (m *LoopbackServerEntity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoopbackServerEntity.Merge(m, src)
}
func (m *LoopbackServerEntity) XXX_Size() int {
	return xxx_messageInfo_LoopbackServerEntity.Size(m)
}
func (m *LoopbackServerEntity) XXX_DiscardUnknown() {
	xxx_messageInfo_LoopbackServerEntity.DiscardUnknown(m)
}

var xxx_messageInfo_LoopbackServerEntity proto.InternalMessageInfo

func (m *LoopbackServerEntity) GetType() LoopbackServerEntity_Type {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return LoopbackServerEntity_UNKNOWN
}

func (m *LoopbackServerEntity) GetEntity() *SyncEntity {
	if m != nil {
		return m.Entity
	}
	return nil
}

func (m *LoopbackServerEntity) GetModelType() int64 {
	if m != nil && m.ModelType != nil {
		return *m.ModelType
	}
	return 0
}

// Contains the loopback server state.
type LoopbackServerProto struct {
	// The protocol buffer format version.
	Version       *int64                  `protobuf:"varint,1,opt,name=version" json:"version,omitempty"`
	StoreBirthday *int64                  `protobuf:"varint,2,opt,name=store_birthday,json=storeBirthday" json:"store_birthday,omitempty"`
	Entities      []*LoopbackServerEntity `protobuf:"bytes,3,rep,name=entities" json:"entities,omitempty"`
	// All Keystore keys known to the server.
	KeystoreKeys []string `protobuf:"bytes,4,rep,name=keystore_keys,json=keystoreKeys" json:"keystore_keys,omitempty"`
	// The last entity ID that was assigned to an entity.
	LastVersionAssigned  *int64   `protobuf:"varint,5,opt,name=last_version_assigned,json=lastVersionAssigned" json:"last_version_assigned,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoopbackServerProto) Reset()         { *m = LoopbackServerProto{} }
func (m *LoopbackServerProto) String() string { return proto.CompactTextString(m) }
func (*LoopbackServerProto) ProtoMessage()    {}
func (*LoopbackServerProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_a041143cb25b822d, []int{1}
}

func (m *LoopbackServerProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoopbackServerProto.Unmarshal(m, b)
}
func (m *LoopbackServerProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoopbackServerProto.Marshal(b, m, deterministic)
}
func (m *LoopbackServerProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoopbackServerProto.Merge(m, src)
}
func (m *LoopbackServerProto) XXX_Size() int {
	return xxx_messageInfo_LoopbackServerProto.Size(m)
}
func (m *LoopbackServerProto) XXX_DiscardUnknown() {
	xxx_messageInfo_LoopbackServerProto.DiscardUnknown(m)
}

var xxx_messageInfo_LoopbackServerProto proto.InternalMessageInfo

func (m *LoopbackServerProto) GetVersion() int64 {
	if m != nil && m.Version != nil {
		return *m.Version
	}
	return 0
}

func (m *LoopbackServerProto) GetStoreBirthday() int64 {
	if m != nil && m.StoreBirthday != nil {
		return *m.StoreBirthday
	}
	return 0
}

func (m *LoopbackServerProto) GetEntities() []*LoopbackServerEntity {
	if m != nil {
		return m.Entities
	}
	return nil
}

func (m *LoopbackServerProto) GetKeystoreKeys() []string {
	if m != nil {
		return m.KeystoreKeys
	}
	return nil
}

func (m *LoopbackServerProto) GetLastVersionAssigned() int64 {
	if m != nil && m.LastVersionAssigned != nil {
		return *m.LastVersionAssigned
	}
	return 0
}

func init() {
	proto.RegisterEnum("sync_pb.LoopbackServerEntity_Type", LoopbackServerEntity_Type_name, LoopbackServerEntity_Type_value)
	proto.RegisterType((*LoopbackServerEntity)(nil), "sync_pb.LoopbackServerEntity")
	proto.RegisterType((*LoopbackServerProto)(nil), "sync_pb.LoopbackServerProto")
}

func init() {
	proto.RegisterFile("loopback_server.proto", fileDescriptor_a041143cb25b822d)
}

var fileDescriptor_a041143cb25b822d = []byte{
	// 379 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x91, 0x51, 0x8b, 0x9b, 0x40,
	0x10, 0xc7, 0xbb, 0xb7, 0xf6, 0x72, 0x99, 0x5c, 0x0e, 0xd9, 0xf4, 0x40, 0x0a, 0x07, 0x62, 0x39,
	0x10, 0x0e, 0x7c, 0xf0, 0xa1, 0xd0, 0xc7, 0x08, 0x42, 0x8b, 0x8d, 0xa6, 0x1b, 0xd3, 0x3e, 0x8a,
	0x31, 0x4b, 0x22, 0x51, 0x57, 0x76, 0xb7, 0x01, 0x3f, 0x71, 0xa1, 0x9f, 0xa2, 0xb8, 0x9a, 0x94,
	0x42, 0xb9, 0x27, 0x67, 0xfe, 0xf3, 0x1b, 0x67, 0xfe, 0xb3, 0xf0, 0x58, 0x71, 0xde, 0xee, 0xf2,
	0xe2, 0x94, 0x49, 0x26, 0xce, 0x4c, 0x78, 0xad, 0xe0, 0x8a, 0x93, 0x89, 0xec, 0x9a, 0x22, 0x6b,
	0x77, 0xef, 0xa1, 0x0f, 0x06, 0xd1, 0xf9, 0x85, 0xe0, 0xdd, 0xd7, 0x11, 0xdf, 0x68, 0x3a, 0x6c,
	0x54, 0xa9, 0x3a, 0xf2, 0x11, 0x0c, 0xd5, 0xb5, 0xcc, 0x42, 0x36, 0x72, 0x1f, 0x7c, 0xc7, 0x1b,
	0x9b, 0xbd, 0xff, 0xc1, 0x5e, 0xda, 0xb5, 0x8c, 0x6a, 0x9e, 0xbc, 0xc0, 0x2d, 0xd3, 0xa2, 0x75,
	0x63, 0x23, 0x77, 0xe6, 0x2f, 0xae, 0x9d, 0x9b, 0xae, 0x29, 0x06, 0x9e, 0x8e, 0x08, 0x79, 0x02,
	0xa8, 0xf9, 0x9e, 0x55, 0x99, 0x1e, 0x85, 0x6d, 0xe4, 0x62, 0x3a, 0xd5, 0x4a, 0xff, 0x47, 0x27,
	0x02, 0xa3, 0xff, 0x92, 0x19, 0x4c, 0xb6, 0x71, 0x14, 0x27, 0x3f, 0x62, 0xf3, 0x0d, 0xb9, 0x87,
	0xbb, 0x20, 0x49, 0xa2, 0xd5, 0x92, 0x46, 0x26, 0x22, 0x73, 0x98, 0xae, 0x43, 0xba, 0x5a, 0xc6,
	0x61, 0x9c, 0x9a, 0x37, 0x7d, 0x9a, 0x26, 0xab, 0x60, 0x93, 0x26, 0x71, 0x68, 0x62, 0x02, 0x70,
	0xbb, 0x8d, 0xbf, 0x7c, 0xdb, 0x86, 0xa6, 0xe1, 0xfc, 0x46, 0xb0, 0xf8, 0x77, 0xf9, 0xb5, 0x3e,
	0x8b, 0x05, 0x93, 0x33, 0x13, 0xb2, 0xe4, 0x8d, 0xf6, 0x8a, 0xe9, 0x25, 0x25, 0xcf, 0xf0, 0x20,
	0x15, 0x17, 0x2c, 0xdb, 0x95, 0x42, 0x1d, 0xf7, 0xf9, 0x60, 0x09, 0xd3, 0xb9, 0x56, 0x83, 0x51,
	0x24, 0x9f, 0xe0, 0x4e, 0xdb, 0x29, 0x99, 0xb4, 0xb0, 0x8d, 0xdd, 0x99, 0xff, 0xf4, 0xea, 0xb5,
	0xe8, 0x15, 0x27, 0x1f, 0x60, 0x7e, 0x62, 0xdd, 0x30, 0xa4, 0x0f, 0x2c, 0xc3, 0xc6, 0xee, 0x94,
	0xde, 0x5f, 0xc4, 0x88, 0x75, 0x92, 0xf8, 0xf0, 0x58, 0xe5, 0x52, 0x65, 0xe3, 0x5a, 0x59, 0x2e,
	0x65, 0x79, 0x68, 0xd8, 0xde, 0x7a, 0xab, 0xb7, 0x59, 0xf4, 0xc5, 0xef, 0x43, 0x6d, 0x39, 0x96,
	0x82, 0x17, 0x78, 0xe6, 0xe2, 0xe0, 0x15, 0x47, 0xc1, 0xeb, 0xf2, 0x67, 0xed, 0x15, 0xbc, 0x6e,
	0x79, 0xc3, 0x1a, 0x25, 0xbd, 0xbf, 0x8f, 0x5f, 0xf0, 0xea, 0x33, 0x5e, 0xa3, 0x3f, 0x01, 0x00,
	0x00, 0xff, 0xff, 0x1f, 0x19, 0xb1, 0x72, 0x30, 0x02, 0x00, 0x00,
}
